//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.AccountServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountServiceReference.Account_servicesSoap")]
    public interface Account_servicesSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Winform.AccountServiceReference.HelloWorldResponse HelloWorld(Winform.AccountServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AccountServiceReference.HelloWorldResponse> HelloWorldAsync(Winform.AccountServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLogin", ReplyAction="*")]
        Winform.AccountServiceReference.CheckLoginResponse CheckLogin(Winform.AccountServiceReference.CheckLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AccountServiceReference.CheckLoginResponse> CheckLoginAsync(Winform.AccountServiceReference.CheckLoginRequest request);
        
        // CODEGEN: Generating message contract since element name getAllAccountSystemResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllAccountSystem", ReplyAction="*")]
        Winform.AccountServiceReference.getAllAccountSystemResponse getAllAccountSystem(Winform.AccountServiceReference.getAllAccountSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllAccountSystem", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AccountServiceReference.getAllAccountSystemResponse> getAllAccountSystemAsync(Winform.AccountServiceReference.getAllAccountSystemRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAccount", ReplyAction="*")]
        Winform.AccountServiceReference.AddAccountResponse AddAccount(Winform.AccountServiceReference.AddAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AccountServiceReference.AddAccountResponse> AddAccountAsync(Winform.AccountServiceReference.AddAccountRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateAccount", ReplyAction="*")]
        Winform.AccountServiceReference.updateAccountResponse updateAccount(Winform.AccountServiceReference.updateAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AccountServiceReference.updateAccountResponse> updateAccountAsync(Winform.AccountServiceReference.updateAccountRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteAccount", ReplyAction="*")]
        Winform.AccountServiceReference.deleteAccountResponse deleteAccount(Winform.AccountServiceReference.deleteAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AccountServiceReference.deleteAccountResponse> deleteAccountAsync(Winform.AccountServiceReference.deleteAccountRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/findAccount", ReplyAction="*")]
        Winform.AccountServiceReference.findAccountResponse findAccount(Winform.AccountServiceReference.findAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/findAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AccountServiceReference.findAccountResponse> findAccountAsync(Winform.AccountServiceReference.findAccountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AccountServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Winform.AccountServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AccountServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Winform.AccountServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckLogin", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AccountServiceReference.CheckLoginRequestBody Body;
        
        public CheckLoginRequest() {
        }
        
        public CheckLoginRequest(Winform.AccountServiceReference.CheckLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public CheckLoginRequestBody() {
        }
        
        public CheckLoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AccountServiceReference.CheckLoginResponseBody Body;
        
        public CheckLoginResponse() {
        }
        
        public CheckLoginResponse(Winform.AccountServiceReference.CheckLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckLoginResult;
        
        public CheckLoginResponseBody() {
        }
        
        public CheckLoginResponseBody(bool CheckLoginResult) {
            this.CheckLoginResult = CheckLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllAccountSystemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllAccountSystem", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AccountServiceReference.getAllAccountSystemRequestBody Body;
        
        public getAllAccountSystemRequest() {
        }
        
        public getAllAccountSystemRequest(Winform.AccountServiceReference.getAllAccountSystemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllAccountSystemRequestBody {
        
        public getAllAccountSystemRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllAccountSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllAccountSystemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AccountServiceReference.getAllAccountSystemResponseBody Body;
        
        public getAllAccountSystemResponse() {
        }
        
        public getAllAccountSystemResponse(Winform.AccountServiceReference.getAllAccountSystemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllAccountSystemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getAllAccountSystemResult;
        
        public getAllAccountSystemResponseBody() {
        }
        
        public getAllAccountSystemResponseBody(string getAllAccountSystemResult) {
            this.getAllAccountSystemResult = getAllAccountSystemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAccount", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AccountServiceReference.AddAccountRequestBody Body;
        
        public AddAccountRequest() {
        }
        
        public AddAccountRequest(Winform.AccountServiceReference.AddAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hoten;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string quyen;
        
        public AddAccountRequestBody() {
        }
        
        public AddAccountRequestBody(string username, string password, string hoten, string email, string quyen) {
            this.username = username;
            this.password = password;
            this.hoten = hoten;
            this.email = email;
            this.quyen = quyen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AccountServiceReference.AddAccountResponseBody Body;
        
        public AddAccountResponse() {
        }
        
        public AddAccountResponse(Winform.AccountServiceReference.AddAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddAccountResponseBody {
        
        public AddAccountResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateAccount", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AccountServiceReference.updateAccountRequestBody Body;
        
        public updateAccountRequest() {
        }
        
        public updateAccountRequest(Winform.AccountServiceReference.updateAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hoten;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string quyen;
        
        public updateAccountRequestBody() {
        }
        
        public updateAccountRequestBody(string username, string password, string hoten, string email, string quyen) {
            this.username = username;
            this.password = password;
            this.hoten = hoten;
            this.email = email;
            this.quyen = quyen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AccountServiceReference.updateAccountResponseBody Body;
        
        public updateAccountResponse() {
        }
        
        public updateAccountResponse(Winform.AccountServiceReference.updateAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateAccountResponseBody {
        
        public updateAccountResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteAccount", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AccountServiceReference.deleteAccountRequestBody Body;
        
        public deleteAccountRequest() {
        }
        
        public deleteAccountRequest(Winform.AccountServiceReference.deleteAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public deleteAccountRequestBody() {
        }
        
        public deleteAccountRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AccountServiceReference.deleteAccountResponseBody Body;
        
        public deleteAccountResponse() {
        }
        
        public deleteAccountResponse(Winform.AccountServiceReference.deleteAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class deleteAccountResponseBody {
        
        public deleteAccountResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findAccount", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AccountServiceReference.findAccountRequestBody Body;
        
        public findAccountRequest() {
        }
        
        public findAccountRequest(Winform.AccountServiceReference.findAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class findAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public findAccountRequestBody() {
        }
        
        public findAccountRequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AccountServiceReference.findAccountResponseBody Body;
        
        public findAccountResponse() {
        }
        
        public findAccountResponse(Winform.AccountServiceReference.findAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class findAccountResponseBody {
        
        public findAccountResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Account_servicesSoapChannel : Winform.AccountServiceReference.Account_servicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Account_servicesSoapClient : System.ServiceModel.ClientBase<Winform.AccountServiceReference.Account_servicesSoap>, Winform.AccountServiceReference.Account_servicesSoap {
        
        public Account_servicesSoapClient() {
        }
        
        public Account_servicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Account_servicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Account_servicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Account_servicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AccountServiceReference.HelloWorldResponse Winform.AccountServiceReference.Account_servicesSoap.HelloWorld(Winform.AccountServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Winform.AccountServiceReference.HelloWorldRequest inValue = new Winform.AccountServiceReference.HelloWorldRequest();
            inValue.Body = new Winform.AccountServiceReference.HelloWorldRequestBody();
            Winform.AccountServiceReference.HelloWorldResponse retVal = ((Winform.AccountServiceReference.Account_servicesSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AccountServiceReference.HelloWorldResponse> Winform.AccountServiceReference.Account_servicesSoap.HelloWorldAsync(Winform.AccountServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AccountServiceReference.HelloWorldResponse> HelloWorldAsync() {
            Winform.AccountServiceReference.HelloWorldRequest inValue = new Winform.AccountServiceReference.HelloWorldRequest();
            inValue.Body = new Winform.AccountServiceReference.HelloWorldRequestBody();
            return ((Winform.AccountServiceReference.Account_servicesSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AccountServiceReference.CheckLoginResponse Winform.AccountServiceReference.Account_servicesSoap.CheckLogin(Winform.AccountServiceReference.CheckLoginRequest request) {
            return base.Channel.CheckLogin(request);
        }
        
        public bool CheckLogin(string username, string password) {
            Winform.AccountServiceReference.CheckLoginRequest inValue = new Winform.AccountServiceReference.CheckLoginRequest();
            inValue.Body = new Winform.AccountServiceReference.CheckLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Winform.AccountServiceReference.CheckLoginResponse retVal = ((Winform.AccountServiceReference.Account_servicesSoap)(this)).CheckLogin(inValue);
            return retVal.Body.CheckLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AccountServiceReference.CheckLoginResponse> Winform.AccountServiceReference.Account_servicesSoap.CheckLoginAsync(Winform.AccountServiceReference.CheckLoginRequest request) {
            return base.Channel.CheckLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AccountServiceReference.CheckLoginResponse> CheckLoginAsync(string username, string password) {
            Winform.AccountServiceReference.CheckLoginRequest inValue = new Winform.AccountServiceReference.CheckLoginRequest();
            inValue.Body = new Winform.AccountServiceReference.CheckLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Winform.AccountServiceReference.Account_servicesSoap)(this)).CheckLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AccountServiceReference.getAllAccountSystemResponse Winform.AccountServiceReference.Account_servicesSoap.getAllAccountSystem(Winform.AccountServiceReference.getAllAccountSystemRequest request) {
            return base.Channel.getAllAccountSystem(request);
        }
        
        public string getAllAccountSystem() {
            Winform.AccountServiceReference.getAllAccountSystemRequest inValue = new Winform.AccountServiceReference.getAllAccountSystemRequest();
            inValue.Body = new Winform.AccountServiceReference.getAllAccountSystemRequestBody();
            Winform.AccountServiceReference.getAllAccountSystemResponse retVal = ((Winform.AccountServiceReference.Account_servicesSoap)(this)).getAllAccountSystem(inValue);
            return retVal.Body.getAllAccountSystemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AccountServiceReference.getAllAccountSystemResponse> Winform.AccountServiceReference.Account_servicesSoap.getAllAccountSystemAsync(Winform.AccountServiceReference.getAllAccountSystemRequest request) {
            return base.Channel.getAllAccountSystemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AccountServiceReference.getAllAccountSystemResponse> getAllAccountSystemAsync() {
            Winform.AccountServiceReference.getAllAccountSystemRequest inValue = new Winform.AccountServiceReference.getAllAccountSystemRequest();
            inValue.Body = new Winform.AccountServiceReference.getAllAccountSystemRequestBody();
            return ((Winform.AccountServiceReference.Account_servicesSoap)(this)).getAllAccountSystemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AccountServiceReference.AddAccountResponse Winform.AccountServiceReference.Account_servicesSoap.AddAccount(Winform.AccountServiceReference.AddAccountRequest request) {
            return base.Channel.AddAccount(request);
        }
        
        public void AddAccount(string username, string password, string hoten, string email, string quyen) {
            Winform.AccountServiceReference.AddAccountRequest inValue = new Winform.AccountServiceReference.AddAccountRequest();
            inValue.Body = new Winform.AccountServiceReference.AddAccountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.hoten = hoten;
            inValue.Body.email = email;
            inValue.Body.quyen = quyen;
            Winform.AccountServiceReference.AddAccountResponse retVal = ((Winform.AccountServiceReference.Account_servicesSoap)(this)).AddAccount(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AccountServiceReference.AddAccountResponse> Winform.AccountServiceReference.Account_servicesSoap.AddAccountAsync(Winform.AccountServiceReference.AddAccountRequest request) {
            return base.Channel.AddAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AccountServiceReference.AddAccountResponse> AddAccountAsync(string username, string password, string hoten, string email, string quyen) {
            Winform.AccountServiceReference.AddAccountRequest inValue = new Winform.AccountServiceReference.AddAccountRequest();
            inValue.Body = new Winform.AccountServiceReference.AddAccountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.hoten = hoten;
            inValue.Body.email = email;
            inValue.Body.quyen = quyen;
            return ((Winform.AccountServiceReference.Account_servicesSoap)(this)).AddAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AccountServiceReference.updateAccountResponse Winform.AccountServiceReference.Account_servicesSoap.updateAccount(Winform.AccountServiceReference.updateAccountRequest request) {
            return base.Channel.updateAccount(request);
        }
        
        public void updateAccount(string username, string password, string hoten, string email, string quyen) {
            Winform.AccountServiceReference.updateAccountRequest inValue = new Winform.AccountServiceReference.updateAccountRequest();
            inValue.Body = new Winform.AccountServiceReference.updateAccountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.hoten = hoten;
            inValue.Body.email = email;
            inValue.Body.quyen = quyen;
            Winform.AccountServiceReference.updateAccountResponse retVal = ((Winform.AccountServiceReference.Account_servicesSoap)(this)).updateAccount(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AccountServiceReference.updateAccountResponse> Winform.AccountServiceReference.Account_servicesSoap.updateAccountAsync(Winform.AccountServiceReference.updateAccountRequest request) {
            return base.Channel.updateAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AccountServiceReference.updateAccountResponse> updateAccountAsync(string username, string password, string hoten, string email, string quyen) {
            Winform.AccountServiceReference.updateAccountRequest inValue = new Winform.AccountServiceReference.updateAccountRequest();
            inValue.Body = new Winform.AccountServiceReference.updateAccountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.hoten = hoten;
            inValue.Body.email = email;
            inValue.Body.quyen = quyen;
            return ((Winform.AccountServiceReference.Account_servicesSoap)(this)).updateAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AccountServiceReference.deleteAccountResponse Winform.AccountServiceReference.Account_servicesSoap.deleteAccount(Winform.AccountServiceReference.deleteAccountRequest request) {
            return base.Channel.deleteAccount(request);
        }
        
        public void deleteAccount(string username) {
            Winform.AccountServiceReference.deleteAccountRequest inValue = new Winform.AccountServiceReference.deleteAccountRequest();
            inValue.Body = new Winform.AccountServiceReference.deleteAccountRequestBody();
            inValue.Body.username = username;
            Winform.AccountServiceReference.deleteAccountResponse retVal = ((Winform.AccountServiceReference.Account_servicesSoap)(this)).deleteAccount(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AccountServiceReference.deleteAccountResponse> Winform.AccountServiceReference.Account_servicesSoap.deleteAccountAsync(Winform.AccountServiceReference.deleteAccountRequest request) {
            return base.Channel.deleteAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AccountServiceReference.deleteAccountResponse> deleteAccountAsync(string username) {
            Winform.AccountServiceReference.deleteAccountRequest inValue = new Winform.AccountServiceReference.deleteAccountRequest();
            inValue.Body = new Winform.AccountServiceReference.deleteAccountRequestBody();
            inValue.Body.username = username;
            return ((Winform.AccountServiceReference.Account_servicesSoap)(this)).deleteAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AccountServiceReference.findAccountResponse Winform.AccountServiceReference.Account_servicesSoap.findAccount(Winform.AccountServiceReference.findAccountRequest request) {
            return base.Channel.findAccount(request);
        }
        
        public void findAccount(string key) {
            Winform.AccountServiceReference.findAccountRequest inValue = new Winform.AccountServiceReference.findAccountRequest();
            inValue.Body = new Winform.AccountServiceReference.findAccountRequestBody();
            inValue.Body.key = key;
            Winform.AccountServiceReference.findAccountResponse retVal = ((Winform.AccountServiceReference.Account_servicesSoap)(this)).findAccount(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AccountServiceReference.findAccountResponse> Winform.AccountServiceReference.Account_servicesSoap.findAccountAsync(Winform.AccountServiceReference.findAccountRequest request) {
            return base.Channel.findAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AccountServiceReference.findAccountResponse> findAccountAsync(string key) {
            Winform.AccountServiceReference.findAccountRequest inValue = new Winform.AccountServiceReference.findAccountRequest();
            inValue.Body = new Winform.AccountServiceReference.findAccountRequestBody();
            inValue.Body.key = key;
            return ((Winform.AccountServiceReference.Account_servicesSoap)(this)).findAccountAsync(inValue);
        }
    }
}
