//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.TeacherServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TeacherServices.Teacher_ServiceSoap")]
    public interface Teacher_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Website.TeacherServices.HelloWorldResponse HelloWorld(Website.TeacherServices.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.TeacherServices.HelloWorldResponse> HelloWorldAsync(Website.TeacherServices.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllLectureResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllLecture", ReplyAction="*")]
        Website.TeacherServices.GetAllLectureResponse GetAllLecture(Website.TeacherServices.GetAllLectureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllLecture", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.TeacherServices.GetAllLectureResponse> GetAllLectureAsync(Website.TeacherServices.GetAllLectureRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllLectureInClassResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllLectureInClass", ReplyAction="*")]
        Website.TeacherServices.GetAllLectureInClassResponse GetAllLectureInClass(Website.TeacherServices.GetAllLectureInClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllLectureInClass", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.TeacherServices.GetAllLectureInClassResponse> GetAllLectureInClassAsync(Website.TeacherServices.GetAllLectureInClassRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllQuestionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllQuestion", ReplyAction="*")]
        Website.TeacherServices.GetAllQuestionResponse GetAllQuestion(Website.TeacherServices.GetAllQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllQuestion", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.TeacherServices.GetAllQuestionResponse> GetAllQuestionAsync(Website.TeacherServices.GetAllQuestionRequest request);
        
        // CODEGEN: Generating message contract since element name GetQuestionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuestion", ReplyAction="*")]
        Website.TeacherServices.GetQuestionResponse GetQuestion(Website.TeacherServices.GetQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuestion", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.TeacherServices.GetQuestionResponse> GetQuestionAsync(Website.TeacherServices.GetQuestionRequest request);
        
        // CODEGEN: Generating message contract since element name GetExamResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExam", ReplyAction="*")]
        Website.TeacherServices.GetExamResponse GetExam(Website.TeacherServices.GetExamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExam", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.TeacherServices.GetExamResponse> GetExamAsync(Website.TeacherServices.GetExamRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllExamResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllExam", ReplyAction="*")]
        Website.TeacherServices.GetAllExamResponse GetAllExam(Website.TeacherServices.GetAllExamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllExam", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.TeacherServices.GetAllExamResponse> GetAllExamAsync(Website.TeacherServices.GetAllExamRequest request);
        
        // CODEGEN: Generating message contract since element name codeLecture from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateLecture", ReplyAction="*")]
        Website.TeacherServices.CreateLectureResponse CreateLecture(Website.TeacherServices.CreateLectureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateLecture", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.TeacherServices.CreateLectureResponse> CreateLectureAsync(Website.TeacherServices.CreateLectureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddLectureToClass", ReplyAction="*")]
        bool AddLectureToClass(int idLecture, int idClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddLectureToClass", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddLectureToClassAsync(int idLecture, int idClass);
        
        // CODEGEN: Generating message contract since element name codeLecture from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAndAddToClass", ReplyAction="*")]
        Website.TeacherServices.CreateAndAddToClassResponse CreateAndAddToClass(Website.TeacherServices.CreateAndAddToClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAndAddToClass", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.TeacherServices.CreateAndAddToClassResponse> CreateAndAddToClassAsync(Website.TeacherServices.CreateAndAddToClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveALectureOfClass", ReplyAction="*")]
        bool RemoveALectureOfClass(int idLecture, int idClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveALectureOfClass", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RemoveALectureOfClassAsync(int idLecture, int idClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveAllLectureOfClass", ReplyAction="*")]
        bool RemoveAllLectureOfClass(int idClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveAllLectureOfClass", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RemoveAllLectureOfClassAsync(int idClass);
        
        // CODEGEN: Generating message contract since element name codeContent from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmptyExamInLecture", ReplyAction="*")]
        Website.TeacherServices.CreateEmptyExamInLectureResponse CreateEmptyExamInLecture(Website.TeacherServices.CreateEmptyExamInLectureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmptyExamInLecture", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.TeacherServices.CreateEmptyExamInLectureResponse> CreateEmptyExamInLectureAsync(Website.TeacherServices.CreateEmptyExamInLectureRequest request);
        
        // CODEGEN: Generating message contract since element name codeQuest from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateQuestMCQ", ReplyAction="*")]
        Website.TeacherServices.CreateQuestMCQResponse CreateQuestMCQ(Website.TeacherServices.CreateQuestMCQRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateQuestMCQ", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.TeacherServices.CreateQuestMCQResponse> CreateQuestMCQAsync(Website.TeacherServices.CreateQuestMCQRequest request);
        
        // CODEGEN: Generating message contract since element name codeAnswer from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAnswerForQuestion", ReplyAction="*")]
        Website.TeacherServices.CreateAnswerForQuestionResponse CreateAnswerForQuestion(Website.TeacherServices.CreateAnswerForQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAnswerForQuestion", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.TeacherServices.CreateAnswerForQuestionResponse> CreateAnswerForQuestionAsync(Website.TeacherServices.CreateAnswerForQuestionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Website.TeacherServices.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Website.TeacherServices.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllLectureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllLecture", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.GetAllLectureRequestBody Body;
        
        public GetAllLectureRequest() {
        }
        
        public GetAllLectureRequest(Website.TeacherServices.GetAllLectureRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllLectureRequestBody {
        
        public GetAllLectureRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllLectureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllLectureResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.GetAllLectureResponseBody Body;
        
        public GetAllLectureResponse() {
        }
        
        public GetAllLectureResponse(Website.TeacherServices.GetAllLectureResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllLectureResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllLectureResult;
        
        public GetAllLectureResponseBody() {
        }
        
        public GetAllLectureResponseBody(string GetAllLectureResult) {
            this.GetAllLectureResult = GetAllLectureResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllLectureInClassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllLectureInClass", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.GetAllLectureInClassRequestBody Body;
        
        public GetAllLectureInClassRequest() {
        }
        
        public GetAllLectureInClassRequest(Website.TeacherServices.GetAllLectureInClassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllLectureInClassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idClass;
        
        public GetAllLectureInClassRequestBody() {
        }
        
        public GetAllLectureInClassRequestBody(int idClass) {
            this.idClass = idClass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllLectureInClassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllLectureInClassResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.GetAllLectureInClassResponseBody Body;
        
        public GetAllLectureInClassResponse() {
        }
        
        public GetAllLectureInClassResponse(Website.TeacherServices.GetAllLectureInClassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllLectureInClassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllLectureInClassResult;
        
        public GetAllLectureInClassResponseBody() {
        }
        
        public GetAllLectureInClassResponseBody(string GetAllLectureInClassResult) {
            this.GetAllLectureInClassResult = GetAllLectureInClassResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllQuestionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllQuestion", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.GetAllQuestionRequestBody Body;
        
        public GetAllQuestionRequest() {
        }
        
        public GetAllQuestionRequest(Website.TeacherServices.GetAllQuestionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllQuestionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idExam;
        
        public GetAllQuestionRequestBody() {
        }
        
        public GetAllQuestionRequestBody(int idExam) {
            this.idExam = idExam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllQuestionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllQuestionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.GetAllQuestionResponseBody Body;
        
        public GetAllQuestionResponse() {
        }
        
        public GetAllQuestionResponse(Website.TeacherServices.GetAllQuestionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllQuestionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllQuestionResult;
        
        public GetAllQuestionResponseBody() {
        }
        
        public GetAllQuestionResponseBody(string GetAllQuestionResult) {
            this.GetAllQuestionResult = GetAllQuestionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuestionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuestion", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.GetQuestionRequestBody Body;
        
        public GetQuestionRequest() {
        }
        
        public GetQuestionRequest(Website.TeacherServices.GetQuestionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQuestionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idQ;
        
        public GetQuestionRequestBody() {
        }
        
        public GetQuestionRequestBody(int idQ) {
            this.idQ = idQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuestionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuestionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.GetQuestionResponseBody Body;
        
        public GetQuestionResponse() {
        }
        
        public GetQuestionResponse(Website.TeacherServices.GetQuestionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQuestionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetQuestionResult;
        
        public GetQuestionResponseBody() {
        }
        
        public GetQuestionResponseBody(string GetQuestionResult) {
            this.GetQuestionResult = GetQuestionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExam", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.GetExamRequestBody Body;
        
        public GetExamRequest() {
        }
        
        public GetExamRequest(Website.TeacherServices.GetExamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idExam;
        
        public GetExamRequestBody() {
        }
        
        public GetExamRequestBody(int idExam) {
            this.idExam = idExam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExamResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.GetExamResponseBody Body;
        
        public GetExamResponse() {
        }
        
        public GetExamResponse(Website.TeacherServices.GetExamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExamResult;
        
        public GetExamResponseBody() {
        }
        
        public GetExamResponseBody(string GetExamResult) {
            this.GetExamResult = GetExamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllExamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllExam", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.GetAllExamRequestBody Body;
        
        public GetAllExamRequest() {
        }
        
        public GetAllExamRequest(Website.TeacherServices.GetAllExamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllExamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idContent;
        
        public GetAllExamRequestBody() {
        }
        
        public GetAllExamRequestBody(int idContent) {
            this.idContent = idContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllExamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllExamResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.GetAllExamResponseBody Body;
        
        public GetAllExamResponse() {
        }
        
        public GetAllExamResponse(Website.TeacherServices.GetAllExamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllExamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllExamResult;
        
        public GetAllExamResponseBody() {
        }
        
        public GetAllExamResponseBody(string GetAllExamResult) {
            this.GetAllExamResult = GetAllExamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateLectureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateLecture", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.CreateLectureRequestBody Body;
        
        public CreateLectureRequest() {
        }
        
        public CreateLectureRequest(Website.TeacherServices.CreateLectureRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateLectureRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codeLecture;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string header;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idTeacher;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int idCourse;
        
        public CreateLectureRequestBody() {
        }
        
        public CreateLectureRequestBody(string codeLecture, string header, string description, int idTeacher, int idCourse) {
            this.codeLecture = codeLecture;
            this.header = header;
            this.description = description;
            this.idTeacher = idTeacher;
            this.idCourse = idCourse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateLectureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateLectureResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.CreateLectureResponseBody Body;
        
        public CreateLectureResponse() {
        }
        
        public CreateLectureResponse(Website.TeacherServices.CreateLectureResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateLectureResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateLectureResult;
        
        public CreateLectureResponseBody() {
        }
        
        public CreateLectureResponseBody(bool CreateLectureResult) {
            this.CreateLectureResult = CreateLectureResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAndAddToClassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAndAddToClass", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.CreateAndAddToClassRequestBody Body;
        
        public CreateAndAddToClassRequest() {
        }
        
        public CreateAndAddToClassRequest(Website.TeacherServices.CreateAndAddToClassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAndAddToClassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codeLecture;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string header;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idTeacher;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int idCourse;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int idClass;
        
        public CreateAndAddToClassRequestBody() {
        }
        
        public CreateAndAddToClassRequestBody(string codeLecture, string header, string description, int idTeacher, int idCourse, int idClass) {
            this.codeLecture = codeLecture;
            this.header = header;
            this.description = description;
            this.idTeacher = idTeacher;
            this.idCourse = idCourse;
            this.idClass = idClass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAndAddToClassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAndAddToClassResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.CreateAndAddToClassResponseBody Body;
        
        public CreateAndAddToClassResponse() {
        }
        
        public CreateAndAddToClassResponse(Website.TeacherServices.CreateAndAddToClassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAndAddToClassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateAndAddToClassResult;
        
        public CreateAndAddToClassResponseBody() {
        }
        
        public CreateAndAddToClassResponseBody(bool CreateAndAddToClassResult) {
            this.CreateAndAddToClassResult = CreateAndAddToClassResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmptyExamInLectureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmptyExamInLecture", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.CreateEmptyExamInLectureRequestBody Body;
        
        public CreateEmptyExamInLectureRequest() {
        }
        
        public CreateEmptyExamInLectureRequest(Website.TeacherServices.CreateEmptyExamInLectureRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEmptyExamInLectureRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codeContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string header;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dayOpen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string dayClose;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dayExipre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string timeStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public float duration;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int idTeacher;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int idLecture;
        
        public CreateEmptyExamInLectureRequestBody() {
        }
        
        public CreateEmptyExamInLectureRequestBody(string codeContent, string header, string description, string dayOpen, string dayClose, string dayExipre, string timeStart, float duration, int idTeacher, int idLecture) {
            this.codeContent = codeContent;
            this.header = header;
            this.description = description;
            this.dayOpen = dayOpen;
            this.dayClose = dayClose;
            this.dayExipre = dayExipre;
            this.timeStart = timeStart;
            this.duration = duration;
            this.idTeacher = idTeacher;
            this.idLecture = idLecture;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmptyExamInLectureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmptyExamInLectureResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.CreateEmptyExamInLectureResponseBody Body;
        
        public CreateEmptyExamInLectureResponse() {
        }
        
        public CreateEmptyExamInLectureResponse(Website.TeacherServices.CreateEmptyExamInLectureResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEmptyExamInLectureResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateEmptyExamInLectureResult;
        
        public CreateEmptyExamInLectureResponseBody() {
        }
        
        public CreateEmptyExamInLectureResponseBody(bool CreateEmptyExamInLectureResult) {
            this.CreateEmptyExamInLectureResult = CreateEmptyExamInLectureResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateQuestMCQRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateQuestMCQ", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.CreateQuestMCQRequestBody Body;
        
        public CreateQuestMCQRequest() {
        }
        
        public CreateQuestMCQRequest(Website.TeacherServices.CreateQuestMCQRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateQuestMCQRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codeQuest;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numberOder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string header;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string img;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int codeContentlec;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string correctAnswer;
        
        public CreateQuestMCQRequestBody() {
        }
        
        public CreateQuestMCQRequestBody(string codeQuest, string numberOder, string header, string content, string img, int codeContentlec, string correctAnswer) {
            this.codeQuest = codeQuest;
            this.numberOder = numberOder;
            this.header = header;
            this.content = content;
            this.img = img;
            this.codeContentlec = codeContentlec;
            this.correctAnswer = correctAnswer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateQuestMCQResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateQuestMCQResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.CreateQuestMCQResponseBody Body;
        
        public CreateQuestMCQResponse() {
        }
        
        public CreateQuestMCQResponse(Website.TeacherServices.CreateQuestMCQResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateQuestMCQResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateQuestMCQResult;
        
        public CreateQuestMCQResponseBody() {
        }
        
        public CreateQuestMCQResponseBody(bool CreateQuestMCQResult) {
            this.CreateQuestMCQResult = CreateQuestMCQResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAnswerForQuestionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAnswerForQuestion", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.CreateAnswerForQuestionRequestBody Body;
        
        public CreateAnswerForQuestionRequest() {
        }
        
        public CreateAnswerForQuestionRequest(Website.TeacherServices.CreateAnswerForQuestionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAnswerForQuestionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codeAnswer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string charOrder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string img;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int codeQuestion;
        
        public CreateAnswerForQuestionRequestBody() {
        }
        
        public CreateAnswerForQuestionRequestBody(string codeAnswer, string charOrder, string content, string img, int codeQuestion) {
            this.codeAnswer = codeAnswer;
            this.charOrder = charOrder;
            this.content = content;
            this.img = img;
            this.codeQuestion = codeQuestion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAnswerForQuestionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAnswerForQuestionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.TeacherServices.CreateAnswerForQuestionResponseBody Body;
        
        public CreateAnswerForQuestionResponse() {
        }
        
        public CreateAnswerForQuestionResponse(Website.TeacherServices.CreateAnswerForQuestionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAnswerForQuestionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateAnswerForQuestionResult;
        
        public CreateAnswerForQuestionResponseBody() {
        }
        
        public CreateAnswerForQuestionResponseBody(bool CreateAnswerForQuestionResult) {
            this.CreateAnswerForQuestionResult = CreateAnswerForQuestionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Teacher_ServiceSoapChannel : Website.TeacherServices.Teacher_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Teacher_ServiceSoapClient : System.ServiceModel.ClientBase<Website.TeacherServices.Teacher_ServiceSoap>, Website.TeacherServices.Teacher_ServiceSoap {
        
        public Teacher_ServiceSoapClient() {
        }
        
        public Teacher_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Teacher_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Teacher_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Teacher_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.TeacherServices.HelloWorldResponse Website.TeacherServices.Teacher_ServiceSoap.HelloWorld(Website.TeacherServices.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Website.TeacherServices.HelloWorldRequest inValue = new Website.TeacherServices.HelloWorldRequest();
            inValue.Body = new Website.TeacherServices.HelloWorldRequestBody();
            Website.TeacherServices.HelloWorldResponse retVal = ((Website.TeacherServices.Teacher_ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.TeacherServices.HelloWorldResponse> Website.TeacherServices.Teacher_ServiceSoap.HelloWorldAsync(Website.TeacherServices.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.TeacherServices.HelloWorldResponse> HelloWorldAsync() {
            Website.TeacherServices.HelloWorldRequest inValue = new Website.TeacherServices.HelloWorldRequest();
            inValue.Body = new Website.TeacherServices.HelloWorldRequestBody();
            return ((Website.TeacherServices.Teacher_ServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.TeacherServices.GetAllLectureResponse Website.TeacherServices.Teacher_ServiceSoap.GetAllLecture(Website.TeacherServices.GetAllLectureRequest request) {
            return base.Channel.GetAllLecture(request);
        }
        
        public string GetAllLecture() {
            Website.TeacherServices.GetAllLectureRequest inValue = new Website.TeacherServices.GetAllLectureRequest();
            inValue.Body = new Website.TeacherServices.GetAllLectureRequestBody();
            Website.TeacherServices.GetAllLectureResponse retVal = ((Website.TeacherServices.Teacher_ServiceSoap)(this)).GetAllLecture(inValue);
            return retVal.Body.GetAllLectureResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.TeacherServices.GetAllLectureResponse> Website.TeacherServices.Teacher_ServiceSoap.GetAllLectureAsync(Website.TeacherServices.GetAllLectureRequest request) {
            return base.Channel.GetAllLectureAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.TeacherServices.GetAllLectureResponse> GetAllLectureAsync() {
            Website.TeacherServices.GetAllLectureRequest inValue = new Website.TeacherServices.GetAllLectureRequest();
            inValue.Body = new Website.TeacherServices.GetAllLectureRequestBody();
            return ((Website.TeacherServices.Teacher_ServiceSoap)(this)).GetAllLectureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.TeacherServices.GetAllLectureInClassResponse Website.TeacherServices.Teacher_ServiceSoap.GetAllLectureInClass(Website.TeacherServices.GetAllLectureInClassRequest request) {
            return base.Channel.GetAllLectureInClass(request);
        }
        
        public string GetAllLectureInClass(int idClass) {
            Website.TeacherServices.GetAllLectureInClassRequest inValue = new Website.TeacherServices.GetAllLectureInClassRequest();
            inValue.Body = new Website.TeacherServices.GetAllLectureInClassRequestBody();
            inValue.Body.idClass = idClass;
            Website.TeacherServices.GetAllLectureInClassResponse retVal = ((Website.TeacherServices.Teacher_ServiceSoap)(this)).GetAllLectureInClass(inValue);
            return retVal.Body.GetAllLectureInClassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.TeacherServices.GetAllLectureInClassResponse> Website.TeacherServices.Teacher_ServiceSoap.GetAllLectureInClassAsync(Website.TeacherServices.GetAllLectureInClassRequest request) {
            return base.Channel.GetAllLectureInClassAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.TeacherServices.GetAllLectureInClassResponse> GetAllLectureInClassAsync(int idClass) {
            Website.TeacherServices.GetAllLectureInClassRequest inValue = new Website.TeacherServices.GetAllLectureInClassRequest();
            inValue.Body = new Website.TeacherServices.GetAllLectureInClassRequestBody();
            inValue.Body.idClass = idClass;
            return ((Website.TeacherServices.Teacher_ServiceSoap)(this)).GetAllLectureInClassAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.TeacherServices.GetAllQuestionResponse Website.TeacherServices.Teacher_ServiceSoap.GetAllQuestion(Website.TeacherServices.GetAllQuestionRequest request) {
            return base.Channel.GetAllQuestion(request);
        }
        
        public string GetAllQuestion(int idExam) {
            Website.TeacherServices.GetAllQuestionRequest inValue = new Website.TeacherServices.GetAllQuestionRequest();
            inValue.Body = new Website.TeacherServices.GetAllQuestionRequestBody();
            inValue.Body.idExam = idExam;
            Website.TeacherServices.GetAllQuestionResponse retVal = ((Website.TeacherServices.Teacher_ServiceSoap)(this)).GetAllQuestion(inValue);
            return retVal.Body.GetAllQuestionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.TeacherServices.GetAllQuestionResponse> Website.TeacherServices.Teacher_ServiceSoap.GetAllQuestionAsync(Website.TeacherServices.GetAllQuestionRequest request) {
            return base.Channel.GetAllQuestionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.TeacherServices.GetAllQuestionResponse> GetAllQuestionAsync(int idExam) {
            Website.TeacherServices.GetAllQuestionRequest inValue = new Website.TeacherServices.GetAllQuestionRequest();
            inValue.Body = new Website.TeacherServices.GetAllQuestionRequestBody();
            inValue.Body.idExam = idExam;
            return ((Website.TeacherServices.Teacher_ServiceSoap)(this)).GetAllQuestionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.TeacherServices.GetQuestionResponse Website.TeacherServices.Teacher_ServiceSoap.GetQuestion(Website.TeacherServices.GetQuestionRequest request) {
            return base.Channel.GetQuestion(request);
        }
        
        public string GetQuestion(int idQ) {
            Website.TeacherServices.GetQuestionRequest inValue = new Website.TeacherServices.GetQuestionRequest();
            inValue.Body = new Website.TeacherServices.GetQuestionRequestBody();
            inValue.Body.idQ = idQ;
            Website.TeacherServices.GetQuestionResponse retVal = ((Website.TeacherServices.Teacher_ServiceSoap)(this)).GetQuestion(inValue);
            return retVal.Body.GetQuestionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.TeacherServices.GetQuestionResponse> Website.TeacherServices.Teacher_ServiceSoap.GetQuestionAsync(Website.TeacherServices.GetQuestionRequest request) {
            return base.Channel.GetQuestionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.TeacherServices.GetQuestionResponse> GetQuestionAsync(int idQ) {
            Website.TeacherServices.GetQuestionRequest inValue = new Website.TeacherServices.GetQuestionRequest();
            inValue.Body = new Website.TeacherServices.GetQuestionRequestBody();
            inValue.Body.idQ = idQ;
            return ((Website.TeacherServices.Teacher_ServiceSoap)(this)).GetQuestionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.TeacherServices.GetExamResponse Website.TeacherServices.Teacher_ServiceSoap.GetExam(Website.TeacherServices.GetExamRequest request) {
            return base.Channel.GetExam(request);
        }
        
        public string GetExam(int idExam) {
            Website.TeacherServices.GetExamRequest inValue = new Website.TeacherServices.GetExamRequest();
            inValue.Body = new Website.TeacherServices.GetExamRequestBody();
            inValue.Body.idExam = idExam;
            Website.TeacherServices.GetExamResponse retVal = ((Website.TeacherServices.Teacher_ServiceSoap)(this)).GetExam(inValue);
            return retVal.Body.GetExamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.TeacherServices.GetExamResponse> Website.TeacherServices.Teacher_ServiceSoap.GetExamAsync(Website.TeacherServices.GetExamRequest request) {
            return base.Channel.GetExamAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.TeacherServices.GetExamResponse> GetExamAsync(int idExam) {
            Website.TeacherServices.GetExamRequest inValue = new Website.TeacherServices.GetExamRequest();
            inValue.Body = new Website.TeacherServices.GetExamRequestBody();
            inValue.Body.idExam = idExam;
            return ((Website.TeacherServices.Teacher_ServiceSoap)(this)).GetExamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.TeacherServices.GetAllExamResponse Website.TeacherServices.Teacher_ServiceSoap.GetAllExam(Website.TeacherServices.GetAllExamRequest request) {
            return base.Channel.GetAllExam(request);
        }
        
        public string GetAllExam(int idContent) {
            Website.TeacherServices.GetAllExamRequest inValue = new Website.TeacherServices.GetAllExamRequest();
            inValue.Body = new Website.TeacherServices.GetAllExamRequestBody();
            inValue.Body.idContent = idContent;
            Website.TeacherServices.GetAllExamResponse retVal = ((Website.TeacherServices.Teacher_ServiceSoap)(this)).GetAllExam(inValue);
            return retVal.Body.GetAllExamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.TeacherServices.GetAllExamResponse> Website.TeacherServices.Teacher_ServiceSoap.GetAllExamAsync(Website.TeacherServices.GetAllExamRequest request) {
            return base.Channel.GetAllExamAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.TeacherServices.GetAllExamResponse> GetAllExamAsync(int idContent) {
            Website.TeacherServices.GetAllExamRequest inValue = new Website.TeacherServices.GetAllExamRequest();
            inValue.Body = new Website.TeacherServices.GetAllExamRequestBody();
            inValue.Body.idContent = idContent;
            return ((Website.TeacherServices.Teacher_ServiceSoap)(this)).GetAllExamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.TeacherServices.CreateLectureResponse Website.TeacherServices.Teacher_ServiceSoap.CreateLecture(Website.TeacherServices.CreateLectureRequest request) {
            return base.Channel.CreateLecture(request);
        }
        
        public bool CreateLecture(string codeLecture, string header, string description, int idTeacher, int idCourse) {
            Website.TeacherServices.CreateLectureRequest inValue = new Website.TeacherServices.CreateLectureRequest();
            inValue.Body = new Website.TeacherServices.CreateLectureRequestBody();
            inValue.Body.codeLecture = codeLecture;
            inValue.Body.header = header;
            inValue.Body.description = description;
            inValue.Body.idTeacher = idTeacher;
            inValue.Body.idCourse = idCourse;
            Website.TeacherServices.CreateLectureResponse retVal = ((Website.TeacherServices.Teacher_ServiceSoap)(this)).CreateLecture(inValue);
            return retVal.Body.CreateLectureResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.TeacherServices.CreateLectureResponse> Website.TeacherServices.Teacher_ServiceSoap.CreateLectureAsync(Website.TeacherServices.CreateLectureRequest request) {
            return base.Channel.CreateLectureAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.TeacherServices.CreateLectureResponse> CreateLectureAsync(string codeLecture, string header, string description, int idTeacher, int idCourse) {
            Website.TeacherServices.CreateLectureRequest inValue = new Website.TeacherServices.CreateLectureRequest();
            inValue.Body = new Website.TeacherServices.CreateLectureRequestBody();
            inValue.Body.codeLecture = codeLecture;
            inValue.Body.header = header;
            inValue.Body.description = description;
            inValue.Body.idTeacher = idTeacher;
            inValue.Body.idCourse = idCourse;
            return ((Website.TeacherServices.Teacher_ServiceSoap)(this)).CreateLectureAsync(inValue);
        }
        
        public bool AddLectureToClass(int idLecture, int idClass) {
            return base.Channel.AddLectureToClass(idLecture, idClass);
        }
        
        public System.Threading.Tasks.Task<bool> AddLectureToClassAsync(int idLecture, int idClass) {
            return base.Channel.AddLectureToClassAsync(idLecture, idClass);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.TeacherServices.CreateAndAddToClassResponse Website.TeacherServices.Teacher_ServiceSoap.CreateAndAddToClass(Website.TeacherServices.CreateAndAddToClassRequest request) {
            return base.Channel.CreateAndAddToClass(request);
        }
        
        public bool CreateAndAddToClass(string codeLecture, string header, string description, int idTeacher, int idCourse, int idClass) {
            Website.TeacherServices.CreateAndAddToClassRequest inValue = new Website.TeacherServices.CreateAndAddToClassRequest();
            inValue.Body = new Website.TeacherServices.CreateAndAddToClassRequestBody();
            inValue.Body.codeLecture = codeLecture;
            inValue.Body.header = header;
            inValue.Body.description = description;
            inValue.Body.idTeacher = idTeacher;
            inValue.Body.idCourse = idCourse;
            inValue.Body.idClass = idClass;
            Website.TeacherServices.CreateAndAddToClassResponse retVal = ((Website.TeacherServices.Teacher_ServiceSoap)(this)).CreateAndAddToClass(inValue);
            return retVal.Body.CreateAndAddToClassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.TeacherServices.CreateAndAddToClassResponse> Website.TeacherServices.Teacher_ServiceSoap.CreateAndAddToClassAsync(Website.TeacherServices.CreateAndAddToClassRequest request) {
            return base.Channel.CreateAndAddToClassAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.TeacherServices.CreateAndAddToClassResponse> CreateAndAddToClassAsync(string codeLecture, string header, string description, int idTeacher, int idCourse, int idClass) {
            Website.TeacherServices.CreateAndAddToClassRequest inValue = new Website.TeacherServices.CreateAndAddToClassRequest();
            inValue.Body = new Website.TeacherServices.CreateAndAddToClassRequestBody();
            inValue.Body.codeLecture = codeLecture;
            inValue.Body.header = header;
            inValue.Body.description = description;
            inValue.Body.idTeacher = idTeacher;
            inValue.Body.idCourse = idCourse;
            inValue.Body.idClass = idClass;
            return ((Website.TeacherServices.Teacher_ServiceSoap)(this)).CreateAndAddToClassAsync(inValue);
        }
        
        public bool RemoveALectureOfClass(int idLecture, int idClass) {
            return base.Channel.RemoveALectureOfClass(idLecture, idClass);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveALectureOfClassAsync(int idLecture, int idClass) {
            return base.Channel.RemoveALectureOfClassAsync(idLecture, idClass);
        }
        
        public bool RemoveAllLectureOfClass(int idClass) {
            return base.Channel.RemoveAllLectureOfClass(idClass);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveAllLectureOfClassAsync(int idClass) {
            return base.Channel.RemoveAllLectureOfClassAsync(idClass);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.TeacherServices.CreateEmptyExamInLectureResponse Website.TeacherServices.Teacher_ServiceSoap.CreateEmptyExamInLecture(Website.TeacherServices.CreateEmptyExamInLectureRequest request) {
            return base.Channel.CreateEmptyExamInLecture(request);
        }
        
        public bool CreateEmptyExamInLecture(string codeContent, string header, string description, string dayOpen, string dayClose, string dayExipre, string timeStart, float duration, int idTeacher, int idLecture) {
            Website.TeacherServices.CreateEmptyExamInLectureRequest inValue = new Website.TeacherServices.CreateEmptyExamInLectureRequest();
            inValue.Body = new Website.TeacherServices.CreateEmptyExamInLectureRequestBody();
            inValue.Body.codeContent = codeContent;
            inValue.Body.header = header;
            inValue.Body.description = description;
            inValue.Body.dayOpen = dayOpen;
            inValue.Body.dayClose = dayClose;
            inValue.Body.dayExipre = dayExipre;
            inValue.Body.timeStart = timeStart;
            inValue.Body.duration = duration;
            inValue.Body.idTeacher = idTeacher;
            inValue.Body.idLecture = idLecture;
            Website.TeacherServices.CreateEmptyExamInLectureResponse retVal = ((Website.TeacherServices.Teacher_ServiceSoap)(this)).CreateEmptyExamInLecture(inValue);
            return retVal.Body.CreateEmptyExamInLectureResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.TeacherServices.CreateEmptyExamInLectureResponse> Website.TeacherServices.Teacher_ServiceSoap.CreateEmptyExamInLectureAsync(Website.TeacherServices.CreateEmptyExamInLectureRequest request) {
            return base.Channel.CreateEmptyExamInLectureAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.TeacherServices.CreateEmptyExamInLectureResponse> CreateEmptyExamInLectureAsync(string codeContent, string header, string description, string dayOpen, string dayClose, string dayExipre, string timeStart, float duration, int idTeacher, int idLecture) {
            Website.TeacherServices.CreateEmptyExamInLectureRequest inValue = new Website.TeacherServices.CreateEmptyExamInLectureRequest();
            inValue.Body = new Website.TeacherServices.CreateEmptyExamInLectureRequestBody();
            inValue.Body.codeContent = codeContent;
            inValue.Body.header = header;
            inValue.Body.description = description;
            inValue.Body.dayOpen = dayOpen;
            inValue.Body.dayClose = dayClose;
            inValue.Body.dayExipre = dayExipre;
            inValue.Body.timeStart = timeStart;
            inValue.Body.duration = duration;
            inValue.Body.idTeacher = idTeacher;
            inValue.Body.idLecture = idLecture;
            return ((Website.TeacherServices.Teacher_ServiceSoap)(this)).CreateEmptyExamInLectureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.TeacherServices.CreateQuestMCQResponse Website.TeacherServices.Teacher_ServiceSoap.CreateQuestMCQ(Website.TeacherServices.CreateQuestMCQRequest request) {
            return base.Channel.CreateQuestMCQ(request);
        }
        
        public bool CreateQuestMCQ(string codeQuest, string numberOder, string header, string content, string img, int codeContentlec, string correctAnswer) {
            Website.TeacherServices.CreateQuestMCQRequest inValue = new Website.TeacherServices.CreateQuestMCQRequest();
            inValue.Body = new Website.TeacherServices.CreateQuestMCQRequestBody();
            inValue.Body.codeQuest = codeQuest;
            inValue.Body.numberOder = numberOder;
            inValue.Body.header = header;
            inValue.Body.content = content;
            inValue.Body.img = img;
            inValue.Body.codeContentlec = codeContentlec;
            inValue.Body.correctAnswer = correctAnswer;
            Website.TeacherServices.CreateQuestMCQResponse retVal = ((Website.TeacherServices.Teacher_ServiceSoap)(this)).CreateQuestMCQ(inValue);
            return retVal.Body.CreateQuestMCQResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.TeacherServices.CreateQuestMCQResponse> Website.TeacherServices.Teacher_ServiceSoap.CreateQuestMCQAsync(Website.TeacherServices.CreateQuestMCQRequest request) {
            return base.Channel.CreateQuestMCQAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.TeacherServices.CreateQuestMCQResponse> CreateQuestMCQAsync(string codeQuest, string numberOder, string header, string content, string img, int codeContentlec, string correctAnswer) {
            Website.TeacherServices.CreateQuestMCQRequest inValue = new Website.TeacherServices.CreateQuestMCQRequest();
            inValue.Body = new Website.TeacherServices.CreateQuestMCQRequestBody();
            inValue.Body.codeQuest = codeQuest;
            inValue.Body.numberOder = numberOder;
            inValue.Body.header = header;
            inValue.Body.content = content;
            inValue.Body.img = img;
            inValue.Body.codeContentlec = codeContentlec;
            inValue.Body.correctAnswer = correctAnswer;
            return ((Website.TeacherServices.Teacher_ServiceSoap)(this)).CreateQuestMCQAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.TeacherServices.CreateAnswerForQuestionResponse Website.TeacherServices.Teacher_ServiceSoap.CreateAnswerForQuestion(Website.TeacherServices.CreateAnswerForQuestionRequest request) {
            return base.Channel.CreateAnswerForQuestion(request);
        }
        
        public bool CreateAnswerForQuestion(string codeAnswer, string charOrder, string content, string img, int codeQuestion) {
            Website.TeacherServices.CreateAnswerForQuestionRequest inValue = new Website.TeacherServices.CreateAnswerForQuestionRequest();
            inValue.Body = new Website.TeacherServices.CreateAnswerForQuestionRequestBody();
            inValue.Body.codeAnswer = codeAnswer;
            inValue.Body.charOrder = charOrder;
            inValue.Body.content = content;
            inValue.Body.img = img;
            inValue.Body.codeQuestion = codeQuestion;
            Website.TeacherServices.CreateAnswerForQuestionResponse retVal = ((Website.TeacherServices.Teacher_ServiceSoap)(this)).CreateAnswerForQuestion(inValue);
            return retVal.Body.CreateAnswerForQuestionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.TeacherServices.CreateAnswerForQuestionResponse> Website.TeacherServices.Teacher_ServiceSoap.CreateAnswerForQuestionAsync(Website.TeacherServices.CreateAnswerForQuestionRequest request) {
            return base.Channel.CreateAnswerForQuestionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.TeacherServices.CreateAnswerForQuestionResponse> CreateAnswerForQuestionAsync(string codeAnswer, string charOrder, string content, string img, int codeQuestion) {
            Website.TeacherServices.CreateAnswerForQuestionRequest inValue = new Website.TeacherServices.CreateAnswerForQuestionRequest();
            inValue.Body = new Website.TeacherServices.CreateAnswerForQuestionRequestBody();
            inValue.Body.codeAnswer = codeAnswer;
            inValue.Body.charOrder = charOrder;
            inValue.Body.content = content;
            inValue.Body.img = img;
            inValue.Body.codeQuestion = codeQuestion;
            return ((Website.TeacherServices.Teacher_ServiceSoap)(this)).CreateAnswerForQuestionAsync(inValue);
        }
    }
}
