//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.AdminService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminService.Admin_ServiceSoap")]
    public interface Admin_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Website.AdminService.HelloWorldResponse HelloWorld(Website.AdminService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.HelloWorldResponse> HelloWorldAsync(Website.AdminService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCourseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCourse", ReplyAction="*")]
        Website.AdminService.GetAllCourseResponse GetAllCourse(Website.AdminService.GetAllCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.GetAllCourseResponse> GetAllCourseAsync(Website.AdminService.GetAllCourseRequest request);
        
        // CODEGEN: Generating message contract since element name GetCourseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCourse", ReplyAction="*")]
        Website.AdminService.GetCourseResponse GetCourse(Website.AdminService.GetCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.GetCourseResponse> GetCourseAsync(Website.AdminService.GetCourseRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllClassCourseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllClassCourse", ReplyAction="*")]
        Website.AdminService.GetAllClassCourseResponse GetAllClassCourse(Website.AdminService.GetAllClassCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.GetAllClassCourseResponse> GetAllClassCourseAsync(Website.AdminService.GetAllClassCourseRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllClassCourseOfCourseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllClassCourseOfCourse", ReplyAction="*")]
        Website.AdminService.GetAllClassCourseOfCourseResponse GetAllClassCourseOfCourse(Website.AdminService.GetAllClassCourseOfCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllClassCourseOfCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.GetAllClassCourseOfCourseResponse> GetAllClassCourseOfCourseAsync(Website.AdminService.GetAllClassCourseOfCourseRequest request);
        
        // CODEGEN: Generating message contract since element name GetClassCourseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClassCourse", ReplyAction="*")]
        Website.AdminService.GetClassCourseResponse GetClassCourse(Website.AdminService.GetClassCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.GetClassCourseResponse> GetClassCourseAsync(Website.AdminService.GetClassCourseRequest request);
        
        // CODEGEN: Generating message contract since element name GetAcountInClassResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAcountInClass", ReplyAction="*")]
        Website.AdminService.GetAcountInClassResponse GetAcountInClass(Website.AdminService.GetAcountInClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAcountInClass", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.GetAcountInClassResponse> GetAcountInClassAsync(Website.AdminService.GetAcountInClassRequest request);
        
        // CODEGEN: Generating message contract since element name GetStudentInSystemResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentInSystem", ReplyAction="*")]
        Website.AdminService.GetStudentInSystemResponse GetStudentInSystem(Website.AdminService.GetStudentInSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentInSystem", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.GetStudentInSystemResponse> GetStudentInSystemAsync(Website.AdminService.GetStudentInSystemRequest request);
        
        // CODEGEN: Generating message contract since element name GetTeacherInSystemResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTeacherInSystem", ReplyAction="*")]
        Website.AdminService.GetTeacherInSystemResponse GetTeacherInSystem(Website.AdminService.GetTeacherInSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTeacherInSystem", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.GetTeacherInSystemResponse> GetTeacherInSystemAsync(Website.AdminService.GetTeacherInSystemRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllStudentInSystemResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStudentInSystem", ReplyAction="*")]
        Website.AdminService.GetAllStudentInSystemResponse GetAllStudentInSystem(Website.AdminService.GetAllStudentInSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStudentInSystem", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.GetAllStudentInSystemResponse> GetAllStudentInSystemAsync(Website.AdminService.GetAllStudentInSystemRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllTeacherInSystemResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTeacherInSystem", ReplyAction="*")]
        Website.AdminService.GetAllTeacherInSystemResponse GetAllTeacherInSystem(Website.AdminService.GetAllTeacherInSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTeacherInSystem", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.GetAllTeacherInSystemResponse> GetAllTeacherInSystemAsync(Website.AdminService.GetAllTeacherInSystemRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllStudentResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStudent", ReplyAction="*")]
        Website.AdminService.GetAllStudentResponse GetAllStudent(Website.AdminService.GetAllStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.GetAllStudentResponse> GetAllStudentAsync(Website.AdminService.GetAllStudentRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllTeacherResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTeacher", ReplyAction="*")]
        Website.AdminService.GetAllTeacherResponse GetAllTeacher(Website.AdminService.GetAllTeacherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTeacher", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.GetAllTeacherResponse> GetAllTeacherAsync(Website.AdminService.GetAllTeacherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStudentToClassCourse", ReplyAction="*")]
        bool AddStudentToClassCourse(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStudentToClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddStudentToClassCourseAsync(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTeacherToClassCourse", ReplyAction="*")]
        bool AddTeacherToClassCourse(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTeacherToClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddTeacherToClassCourseAsync(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveStudentToClassCourse", ReplyAction="*")]
        bool RemoveStudentToClassCourse(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveStudentToClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RemoveStudentToClassCourseAsync(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveAllStudentToClassCourse", ReplyAction="*")]
        bool RemoveAllStudentToClassCourse(int idClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveAllStudentToClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RemoveAllStudentToClassCourseAsync(int idClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveTeacherToClassCourse", ReplyAction="*")]
        bool RemoveTeacherToClassCourse(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveTeacherToClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RemoveTeacherToClassCourseAsync(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveAllTeacherToClassCourse", ReplyAction="*")]
        bool RemoveAllTeacherToClassCourse(int idClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveAllTeacherToClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RemoveAllTeacherToClassCourseAsync(int idClass);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindStudentInSystem", ReplyAction="*")]
        Website.AdminService.FindStudentInSystemResponse FindStudentInSystem(Website.AdminService.FindStudentInSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindStudentInSystem", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.FindStudentInSystemResponse> FindStudentInSystemAsync(Website.AdminService.FindStudentInSystemRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindTeacherInSystem", ReplyAction="*")]
        Website.AdminService.FindTeacherInSystemResponse FindTeacherInSystem(Website.AdminService.FindTeacherInSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindTeacherInSystem", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.FindTeacherInSystemResponse> FindTeacherInSystemAsync(Website.AdminService.FindTeacherInSystemRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindStudentInClass", ReplyAction="*")]
        Website.AdminService.FindStudentInClassResponse FindStudentInClass(Website.AdminService.FindStudentInClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindStudentInClass", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.FindStudentInClassResponse> FindStudentInClassAsync(Website.AdminService.FindStudentInClassRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindTeacherInClass", ReplyAction="*")]
        Website.AdminService.FindTeacherInClassResponse FindTeacherInClass(Website.AdminService.FindTeacherInClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindTeacherInClass", ReplyAction="*")]
        System.Threading.Tasks.Task<Website.AdminService.FindTeacherInClassResponse> FindTeacherInClassAsync(Website.AdminService.FindTeacherInClassRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Website.AdminService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Website.AdminService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCourse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAllCourseRequestBody Body;
        
        public GetAllCourseRequest() {
        }
        
        public GetAllCourseRequest(Website.AdminService.GetAllCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCourseRequestBody {
        
        public GetAllCourseRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAllCourseResponseBody Body;
        
        public GetAllCourseResponse() {
        }
        
        public GetAllCourseResponse(Website.AdminService.GetAllCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllCourseResult;
        
        public GetAllCourseResponseBody() {
        }
        
        public GetAllCourseResponseBody(string GetAllCourseResult) {
            this.GetAllCourseResult = GetAllCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetCourseRequestBody Body;
        
        public GetCourseRequest() {
        }
        
        public GetCourseRequest(Website.AdminService.GetCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCourseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetCourseRequestBody() {
        }
        
        public GetCourseRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetCourseResponseBody Body;
        
        public GetCourseResponse() {
        }
        
        public GetCourseResponse(Website.AdminService.GetCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCourseResult;
        
        public GetCourseResponseBody() {
        }
        
        public GetCourseResponseBody(string GetCourseResult) {
            this.GetCourseResult = GetCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllClassCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllClassCourse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAllClassCourseRequestBody Body;
        
        public GetAllClassCourseRequest() {
        }
        
        public GetAllClassCourseRequest(Website.AdminService.GetAllClassCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllClassCourseRequestBody {
        
        public GetAllClassCourseRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllClassCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllClassCourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAllClassCourseResponseBody Body;
        
        public GetAllClassCourseResponse() {
        }
        
        public GetAllClassCourseResponse(Website.AdminService.GetAllClassCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllClassCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllClassCourseResult;
        
        public GetAllClassCourseResponseBody() {
        }
        
        public GetAllClassCourseResponseBody(string GetAllClassCourseResult) {
            this.GetAllClassCourseResult = GetAllClassCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllClassCourseOfCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllClassCourseOfCourse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAllClassCourseOfCourseRequestBody Body;
        
        public GetAllClassCourseOfCourseRequest() {
        }
        
        public GetAllClassCourseOfCourseRequest(Website.AdminService.GetAllClassCourseOfCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllClassCourseOfCourseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetAllClassCourseOfCourseRequestBody() {
        }
        
        public GetAllClassCourseOfCourseRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllClassCourseOfCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllClassCourseOfCourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAllClassCourseOfCourseResponseBody Body;
        
        public GetAllClassCourseOfCourseResponse() {
        }
        
        public GetAllClassCourseOfCourseResponse(Website.AdminService.GetAllClassCourseOfCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllClassCourseOfCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllClassCourseOfCourseResult;
        
        public GetAllClassCourseOfCourseResponseBody() {
        }
        
        public GetAllClassCourseOfCourseResponseBody(string GetAllClassCourseOfCourseResult) {
            this.GetAllClassCourseOfCourseResult = GetAllClassCourseOfCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClassCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClassCourse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetClassCourseRequestBody Body;
        
        public GetClassCourseRequest() {
        }
        
        public GetClassCourseRequest(Website.AdminService.GetClassCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetClassCourseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetClassCourseRequestBody() {
        }
        
        public GetClassCourseRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClassCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClassCourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetClassCourseResponseBody Body;
        
        public GetClassCourseResponse() {
        }
        
        public GetClassCourseResponse(Website.AdminService.GetClassCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetClassCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetClassCourseResult;
        
        public GetClassCourseResponseBody() {
        }
        
        public GetClassCourseResponseBody(string GetClassCourseResult) {
            this.GetClassCourseResult = GetClassCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAcountInClassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAcountInClass", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAcountInClassRequestBody Body;
        
        public GetAcountInClassRequest() {
        }
        
        public GetAcountInClassRequest(Website.AdminService.GetAcountInClassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAcountInClassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idClass;
        
        public GetAcountInClassRequestBody() {
        }
        
        public GetAcountInClassRequestBody(int idClass) {
            this.idClass = idClass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAcountInClassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAcountInClassResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAcountInClassResponseBody Body;
        
        public GetAcountInClassResponse() {
        }
        
        public GetAcountInClassResponse(Website.AdminService.GetAcountInClassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAcountInClassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAcountInClassResult;
        
        public GetAcountInClassResponseBody() {
        }
        
        public GetAcountInClassResponseBody(string GetAcountInClassResult) {
            this.GetAcountInClassResult = GetAcountInClassResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentInSystemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentInSystem", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetStudentInSystemRequestBody Body;
        
        public GetStudentInSystemRequest() {
        }
        
        public GetStudentInSystemRequest(Website.AdminService.GetStudentInSystemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentInSystemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetStudentInSystemRequestBody() {
        }
        
        public GetStudentInSystemRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentInSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentInSystemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetStudentInSystemResponseBody Body;
        
        public GetStudentInSystemResponse() {
        }
        
        public GetStudentInSystemResponse(Website.AdminService.GetStudentInSystemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentInSystemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStudentInSystemResult;
        
        public GetStudentInSystemResponseBody() {
        }
        
        public GetStudentInSystemResponseBody(string GetStudentInSystemResult) {
            this.GetStudentInSystemResult = GetStudentInSystemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTeacherInSystemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTeacherInSystem", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetTeacherInSystemRequestBody Body;
        
        public GetTeacherInSystemRequest() {
        }
        
        public GetTeacherInSystemRequest(Website.AdminService.GetTeacherInSystemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTeacherInSystemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetTeacherInSystemRequestBody() {
        }
        
        public GetTeacherInSystemRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTeacherInSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTeacherInSystemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetTeacherInSystemResponseBody Body;
        
        public GetTeacherInSystemResponse() {
        }
        
        public GetTeacherInSystemResponse(Website.AdminService.GetTeacherInSystemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTeacherInSystemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTeacherInSystemResult;
        
        public GetTeacherInSystemResponseBody() {
        }
        
        public GetTeacherInSystemResponseBody(string GetTeacherInSystemResult) {
            this.GetTeacherInSystemResult = GetTeacherInSystemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStudentInSystemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStudentInSystem", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAllStudentInSystemRequestBody Body;
        
        public GetAllStudentInSystemRequest() {
        }
        
        public GetAllStudentInSystemRequest(Website.AdminService.GetAllStudentInSystemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllStudentInSystemRequestBody {
        
        public GetAllStudentInSystemRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStudentInSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStudentInSystemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAllStudentInSystemResponseBody Body;
        
        public GetAllStudentInSystemResponse() {
        }
        
        public GetAllStudentInSystemResponse(Website.AdminService.GetAllStudentInSystemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllStudentInSystemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllStudentInSystemResult;
        
        public GetAllStudentInSystemResponseBody() {
        }
        
        public GetAllStudentInSystemResponseBody(string GetAllStudentInSystemResult) {
            this.GetAllStudentInSystemResult = GetAllStudentInSystemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTeacherInSystemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTeacherInSystem", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAllTeacherInSystemRequestBody Body;
        
        public GetAllTeacherInSystemRequest() {
        }
        
        public GetAllTeacherInSystemRequest(Website.AdminService.GetAllTeacherInSystemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTeacherInSystemRequestBody {
        
        public GetAllTeacherInSystemRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTeacherInSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTeacherInSystemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAllTeacherInSystemResponseBody Body;
        
        public GetAllTeacherInSystemResponse() {
        }
        
        public GetAllTeacherInSystemResponse(Website.AdminService.GetAllTeacherInSystemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTeacherInSystemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllTeacherInSystemResult;
        
        public GetAllTeacherInSystemResponseBody() {
        }
        
        public GetAllTeacherInSystemResponseBody(string GetAllTeacherInSystemResult) {
            this.GetAllTeacherInSystemResult = GetAllTeacherInSystemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStudent", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAllStudentRequestBody Body;
        
        public GetAllStudentRequest() {
        }
        
        public GetAllStudentRequest(Website.AdminService.GetAllStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idClass;
        
        public GetAllStudentRequestBody() {
        }
        
        public GetAllStudentRequestBody(int idClass) {
            this.idClass = idClass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAllStudentResponseBody Body;
        
        public GetAllStudentResponse() {
        }
        
        public GetAllStudentResponse(Website.AdminService.GetAllStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllStudentResult;
        
        public GetAllStudentResponseBody() {
        }
        
        public GetAllStudentResponseBody(string GetAllStudentResult) {
            this.GetAllStudentResult = GetAllStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTeacherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTeacher", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAllTeacherRequestBody Body;
        
        public GetAllTeacherRequest() {
        }
        
        public GetAllTeacherRequest(Website.AdminService.GetAllTeacherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTeacherRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idClass;
        
        public GetAllTeacherRequestBody() {
        }
        
        public GetAllTeacherRequestBody(int idClass) {
            this.idClass = idClass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTeacherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTeacherResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.GetAllTeacherResponseBody Body;
        
        public GetAllTeacherResponse() {
        }
        
        public GetAllTeacherResponse(Website.AdminService.GetAllTeacherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTeacherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllTeacherResult;
        
        public GetAllTeacherResponseBody() {
        }
        
        public GetAllTeacherResponseBody(string GetAllTeacherResult) {
            this.GetAllTeacherResult = GetAllTeacherResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindStudentInSystemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindStudentInSystem", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.FindStudentInSystemRequestBody Body;
        
        public FindStudentInSystemRequest() {
        }
        
        public FindStudentInSystemRequest(Website.AdminService.FindStudentInSystemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindStudentInSystemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public FindStudentInSystemRequestBody() {
        }
        
        public FindStudentInSystemRequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindStudentInSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindStudentInSystemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.FindStudentInSystemResponseBody Body;
        
        public FindStudentInSystemResponse() {
        }
        
        public FindStudentInSystemResponse(Website.AdminService.FindStudentInSystemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindStudentInSystemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindStudentInSystemResult;
        
        public FindStudentInSystemResponseBody() {
        }
        
        public FindStudentInSystemResponseBody(string FindStudentInSystemResult) {
            this.FindStudentInSystemResult = FindStudentInSystemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindTeacherInSystemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindTeacherInSystem", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.FindTeacherInSystemRequestBody Body;
        
        public FindTeacherInSystemRequest() {
        }
        
        public FindTeacherInSystemRequest(Website.AdminService.FindTeacherInSystemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindTeacherInSystemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public FindTeacherInSystemRequestBody() {
        }
        
        public FindTeacherInSystemRequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindTeacherInSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindTeacherInSystemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.FindTeacherInSystemResponseBody Body;
        
        public FindTeacherInSystemResponse() {
        }
        
        public FindTeacherInSystemResponse(Website.AdminService.FindTeacherInSystemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindTeacherInSystemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindTeacherInSystemResult;
        
        public FindTeacherInSystemResponseBody() {
        }
        
        public FindTeacherInSystemResponseBody(string FindTeacherInSystemResult) {
            this.FindTeacherInSystemResult = FindTeacherInSystemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindStudentInClassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindStudentInClass", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.FindStudentInClassRequestBody Body;
        
        public FindStudentInClassRequest() {
        }
        
        public FindStudentInClassRequest(Website.AdminService.FindStudentInClassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindStudentInClassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idClass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        public FindStudentInClassRequestBody() {
        }
        
        public FindStudentInClassRequestBody(int idClass, string key) {
            this.idClass = idClass;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindStudentInClassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindStudentInClassResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.FindStudentInClassResponseBody Body;
        
        public FindStudentInClassResponse() {
        }
        
        public FindStudentInClassResponse(Website.AdminService.FindStudentInClassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindStudentInClassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindStudentInClassResult;
        
        public FindStudentInClassResponseBody() {
        }
        
        public FindStudentInClassResponseBody(string FindStudentInClassResult) {
            this.FindStudentInClassResult = FindStudentInClassResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindTeacherInClassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindTeacherInClass", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.FindTeacherInClassRequestBody Body;
        
        public FindTeacherInClassRequest() {
        }
        
        public FindTeacherInClassRequest(Website.AdminService.FindTeacherInClassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindTeacherInClassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idClass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        public FindTeacherInClassRequestBody() {
        }
        
        public FindTeacherInClassRequestBody(int idClass, string key) {
            this.idClass = idClass;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindTeacherInClassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindTeacherInClassResponse", Namespace="http://tempuri.org/", Order=0)]
        public Website.AdminService.FindTeacherInClassResponseBody Body;
        
        public FindTeacherInClassResponse() {
        }
        
        public FindTeacherInClassResponse(Website.AdminService.FindTeacherInClassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindTeacherInClassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindTeacherInClassResult;
        
        public FindTeacherInClassResponseBody() {
        }
        
        public FindTeacherInClassResponseBody(string FindTeacherInClassResult) {
            this.FindTeacherInClassResult = FindTeacherInClassResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Admin_ServiceSoapChannel : Website.AdminService.Admin_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Admin_ServiceSoapClient : System.ServiceModel.ClientBase<Website.AdminService.Admin_ServiceSoap>, Website.AdminService.Admin_ServiceSoap {
        
        public Admin_ServiceSoapClient() {
        }
        
        public Admin_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Admin_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Admin_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Admin_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.HelloWorldResponse Website.AdminService.Admin_ServiceSoap.HelloWorld(Website.AdminService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Website.AdminService.HelloWorldRequest inValue = new Website.AdminService.HelloWorldRequest();
            inValue.Body = new Website.AdminService.HelloWorldRequestBody();
            Website.AdminService.HelloWorldResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.HelloWorldResponse> Website.AdminService.Admin_ServiceSoap.HelloWorldAsync(Website.AdminService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.HelloWorldResponse> HelloWorldAsync() {
            Website.AdminService.HelloWorldRequest inValue = new Website.AdminService.HelloWorldRequest();
            inValue.Body = new Website.AdminService.HelloWorldRequestBody();
            return ((Website.AdminService.Admin_ServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.GetAllCourseResponse Website.AdminService.Admin_ServiceSoap.GetAllCourse(Website.AdminService.GetAllCourseRequest request) {
            return base.Channel.GetAllCourse(request);
        }
        
        public string GetAllCourse() {
            Website.AdminService.GetAllCourseRequest inValue = new Website.AdminService.GetAllCourseRequest();
            inValue.Body = new Website.AdminService.GetAllCourseRequestBody();
            Website.AdminService.GetAllCourseResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).GetAllCourse(inValue);
            return retVal.Body.GetAllCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.GetAllCourseResponse> Website.AdminService.Admin_ServiceSoap.GetAllCourseAsync(Website.AdminService.GetAllCourseRequest request) {
            return base.Channel.GetAllCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.GetAllCourseResponse> GetAllCourseAsync() {
            Website.AdminService.GetAllCourseRequest inValue = new Website.AdminService.GetAllCourseRequest();
            inValue.Body = new Website.AdminService.GetAllCourseRequestBody();
            return ((Website.AdminService.Admin_ServiceSoap)(this)).GetAllCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.GetCourseResponse Website.AdminService.Admin_ServiceSoap.GetCourse(Website.AdminService.GetCourseRequest request) {
            return base.Channel.GetCourse(request);
        }
        
        public string GetCourse(int id) {
            Website.AdminService.GetCourseRequest inValue = new Website.AdminService.GetCourseRequest();
            inValue.Body = new Website.AdminService.GetCourseRequestBody();
            inValue.Body.id = id;
            Website.AdminService.GetCourseResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).GetCourse(inValue);
            return retVal.Body.GetCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.GetCourseResponse> Website.AdminService.Admin_ServiceSoap.GetCourseAsync(Website.AdminService.GetCourseRequest request) {
            return base.Channel.GetCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.GetCourseResponse> GetCourseAsync(int id) {
            Website.AdminService.GetCourseRequest inValue = new Website.AdminService.GetCourseRequest();
            inValue.Body = new Website.AdminService.GetCourseRequestBody();
            inValue.Body.id = id;
            return ((Website.AdminService.Admin_ServiceSoap)(this)).GetCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.GetAllClassCourseResponse Website.AdminService.Admin_ServiceSoap.GetAllClassCourse(Website.AdminService.GetAllClassCourseRequest request) {
            return base.Channel.GetAllClassCourse(request);
        }
        
        public string GetAllClassCourse() {
            Website.AdminService.GetAllClassCourseRequest inValue = new Website.AdminService.GetAllClassCourseRequest();
            inValue.Body = new Website.AdminService.GetAllClassCourseRequestBody();
            Website.AdminService.GetAllClassCourseResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).GetAllClassCourse(inValue);
            return retVal.Body.GetAllClassCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.GetAllClassCourseResponse> Website.AdminService.Admin_ServiceSoap.GetAllClassCourseAsync(Website.AdminService.GetAllClassCourseRequest request) {
            return base.Channel.GetAllClassCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.GetAllClassCourseResponse> GetAllClassCourseAsync() {
            Website.AdminService.GetAllClassCourseRequest inValue = new Website.AdminService.GetAllClassCourseRequest();
            inValue.Body = new Website.AdminService.GetAllClassCourseRequestBody();
            return ((Website.AdminService.Admin_ServiceSoap)(this)).GetAllClassCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.GetAllClassCourseOfCourseResponse Website.AdminService.Admin_ServiceSoap.GetAllClassCourseOfCourse(Website.AdminService.GetAllClassCourseOfCourseRequest request) {
            return base.Channel.GetAllClassCourseOfCourse(request);
        }
        
        public string GetAllClassCourseOfCourse(int id) {
            Website.AdminService.GetAllClassCourseOfCourseRequest inValue = new Website.AdminService.GetAllClassCourseOfCourseRequest();
            inValue.Body = new Website.AdminService.GetAllClassCourseOfCourseRequestBody();
            inValue.Body.id = id;
            Website.AdminService.GetAllClassCourseOfCourseResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).GetAllClassCourseOfCourse(inValue);
            return retVal.Body.GetAllClassCourseOfCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.GetAllClassCourseOfCourseResponse> Website.AdminService.Admin_ServiceSoap.GetAllClassCourseOfCourseAsync(Website.AdminService.GetAllClassCourseOfCourseRequest request) {
            return base.Channel.GetAllClassCourseOfCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.GetAllClassCourseOfCourseResponse> GetAllClassCourseOfCourseAsync(int id) {
            Website.AdminService.GetAllClassCourseOfCourseRequest inValue = new Website.AdminService.GetAllClassCourseOfCourseRequest();
            inValue.Body = new Website.AdminService.GetAllClassCourseOfCourseRequestBody();
            inValue.Body.id = id;
            return ((Website.AdminService.Admin_ServiceSoap)(this)).GetAllClassCourseOfCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.GetClassCourseResponse Website.AdminService.Admin_ServiceSoap.GetClassCourse(Website.AdminService.GetClassCourseRequest request) {
            return base.Channel.GetClassCourse(request);
        }
        
        public string GetClassCourse(int id) {
            Website.AdminService.GetClassCourseRequest inValue = new Website.AdminService.GetClassCourseRequest();
            inValue.Body = new Website.AdminService.GetClassCourseRequestBody();
            inValue.Body.id = id;
            Website.AdminService.GetClassCourseResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).GetClassCourse(inValue);
            return retVal.Body.GetClassCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.GetClassCourseResponse> Website.AdminService.Admin_ServiceSoap.GetClassCourseAsync(Website.AdminService.GetClassCourseRequest request) {
            return base.Channel.GetClassCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.GetClassCourseResponse> GetClassCourseAsync(int id) {
            Website.AdminService.GetClassCourseRequest inValue = new Website.AdminService.GetClassCourseRequest();
            inValue.Body = new Website.AdminService.GetClassCourseRequestBody();
            inValue.Body.id = id;
            return ((Website.AdminService.Admin_ServiceSoap)(this)).GetClassCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.GetAcountInClassResponse Website.AdminService.Admin_ServiceSoap.GetAcountInClass(Website.AdminService.GetAcountInClassRequest request) {
            return base.Channel.GetAcountInClass(request);
        }
        
        public string GetAcountInClass(int idClass) {
            Website.AdminService.GetAcountInClassRequest inValue = new Website.AdminService.GetAcountInClassRequest();
            inValue.Body = new Website.AdminService.GetAcountInClassRequestBody();
            inValue.Body.idClass = idClass;
            Website.AdminService.GetAcountInClassResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).GetAcountInClass(inValue);
            return retVal.Body.GetAcountInClassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.GetAcountInClassResponse> Website.AdminService.Admin_ServiceSoap.GetAcountInClassAsync(Website.AdminService.GetAcountInClassRequest request) {
            return base.Channel.GetAcountInClassAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.GetAcountInClassResponse> GetAcountInClassAsync(int idClass) {
            Website.AdminService.GetAcountInClassRequest inValue = new Website.AdminService.GetAcountInClassRequest();
            inValue.Body = new Website.AdminService.GetAcountInClassRequestBody();
            inValue.Body.idClass = idClass;
            return ((Website.AdminService.Admin_ServiceSoap)(this)).GetAcountInClassAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.GetStudentInSystemResponse Website.AdminService.Admin_ServiceSoap.GetStudentInSystem(Website.AdminService.GetStudentInSystemRequest request) {
            return base.Channel.GetStudentInSystem(request);
        }
        
        public string GetStudentInSystem(int id) {
            Website.AdminService.GetStudentInSystemRequest inValue = new Website.AdminService.GetStudentInSystemRequest();
            inValue.Body = new Website.AdminService.GetStudentInSystemRequestBody();
            inValue.Body.id = id;
            Website.AdminService.GetStudentInSystemResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).GetStudentInSystem(inValue);
            return retVal.Body.GetStudentInSystemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.GetStudentInSystemResponse> Website.AdminService.Admin_ServiceSoap.GetStudentInSystemAsync(Website.AdminService.GetStudentInSystemRequest request) {
            return base.Channel.GetStudentInSystemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.GetStudentInSystemResponse> GetStudentInSystemAsync(int id) {
            Website.AdminService.GetStudentInSystemRequest inValue = new Website.AdminService.GetStudentInSystemRequest();
            inValue.Body = new Website.AdminService.GetStudentInSystemRequestBody();
            inValue.Body.id = id;
            return ((Website.AdminService.Admin_ServiceSoap)(this)).GetStudentInSystemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.GetTeacherInSystemResponse Website.AdminService.Admin_ServiceSoap.GetTeacherInSystem(Website.AdminService.GetTeacherInSystemRequest request) {
            return base.Channel.GetTeacherInSystem(request);
        }
        
        public string GetTeacherInSystem(int id) {
            Website.AdminService.GetTeacherInSystemRequest inValue = new Website.AdminService.GetTeacherInSystemRequest();
            inValue.Body = new Website.AdminService.GetTeacherInSystemRequestBody();
            inValue.Body.id = id;
            Website.AdminService.GetTeacherInSystemResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).GetTeacherInSystem(inValue);
            return retVal.Body.GetTeacherInSystemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.GetTeacherInSystemResponse> Website.AdminService.Admin_ServiceSoap.GetTeacherInSystemAsync(Website.AdminService.GetTeacherInSystemRequest request) {
            return base.Channel.GetTeacherInSystemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.GetTeacherInSystemResponse> GetTeacherInSystemAsync(int id) {
            Website.AdminService.GetTeacherInSystemRequest inValue = new Website.AdminService.GetTeacherInSystemRequest();
            inValue.Body = new Website.AdminService.GetTeacherInSystemRequestBody();
            inValue.Body.id = id;
            return ((Website.AdminService.Admin_ServiceSoap)(this)).GetTeacherInSystemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.GetAllStudentInSystemResponse Website.AdminService.Admin_ServiceSoap.GetAllStudentInSystem(Website.AdminService.GetAllStudentInSystemRequest request) {
            return base.Channel.GetAllStudentInSystem(request);
        }
        
        public string GetAllStudentInSystem() {
            Website.AdminService.GetAllStudentInSystemRequest inValue = new Website.AdminService.GetAllStudentInSystemRequest();
            inValue.Body = new Website.AdminService.GetAllStudentInSystemRequestBody();
            Website.AdminService.GetAllStudentInSystemResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).GetAllStudentInSystem(inValue);
            return retVal.Body.GetAllStudentInSystemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.GetAllStudentInSystemResponse> Website.AdminService.Admin_ServiceSoap.GetAllStudentInSystemAsync(Website.AdminService.GetAllStudentInSystemRequest request) {
            return base.Channel.GetAllStudentInSystemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.GetAllStudentInSystemResponse> GetAllStudentInSystemAsync() {
            Website.AdminService.GetAllStudentInSystemRequest inValue = new Website.AdminService.GetAllStudentInSystemRequest();
            inValue.Body = new Website.AdminService.GetAllStudentInSystemRequestBody();
            return ((Website.AdminService.Admin_ServiceSoap)(this)).GetAllStudentInSystemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.GetAllTeacherInSystemResponse Website.AdminService.Admin_ServiceSoap.GetAllTeacherInSystem(Website.AdminService.GetAllTeacherInSystemRequest request) {
            return base.Channel.GetAllTeacherInSystem(request);
        }
        
        public string GetAllTeacherInSystem() {
            Website.AdminService.GetAllTeacherInSystemRequest inValue = new Website.AdminService.GetAllTeacherInSystemRequest();
            inValue.Body = new Website.AdminService.GetAllTeacherInSystemRequestBody();
            Website.AdminService.GetAllTeacherInSystemResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).GetAllTeacherInSystem(inValue);
            return retVal.Body.GetAllTeacherInSystemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.GetAllTeacherInSystemResponse> Website.AdminService.Admin_ServiceSoap.GetAllTeacherInSystemAsync(Website.AdminService.GetAllTeacherInSystemRequest request) {
            return base.Channel.GetAllTeacherInSystemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.GetAllTeacherInSystemResponse> GetAllTeacherInSystemAsync() {
            Website.AdminService.GetAllTeacherInSystemRequest inValue = new Website.AdminService.GetAllTeacherInSystemRequest();
            inValue.Body = new Website.AdminService.GetAllTeacherInSystemRequestBody();
            return ((Website.AdminService.Admin_ServiceSoap)(this)).GetAllTeacherInSystemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.GetAllStudentResponse Website.AdminService.Admin_ServiceSoap.GetAllStudent(Website.AdminService.GetAllStudentRequest request) {
            return base.Channel.GetAllStudent(request);
        }
        
        public string GetAllStudent(int idClass) {
            Website.AdminService.GetAllStudentRequest inValue = new Website.AdminService.GetAllStudentRequest();
            inValue.Body = new Website.AdminService.GetAllStudentRequestBody();
            inValue.Body.idClass = idClass;
            Website.AdminService.GetAllStudentResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).GetAllStudent(inValue);
            return retVal.Body.GetAllStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.GetAllStudentResponse> Website.AdminService.Admin_ServiceSoap.GetAllStudentAsync(Website.AdminService.GetAllStudentRequest request) {
            return base.Channel.GetAllStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.GetAllStudentResponse> GetAllStudentAsync(int idClass) {
            Website.AdminService.GetAllStudentRequest inValue = new Website.AdminService.GetAllStudentRequest();
            inValue.Body = new Website.AdminService.GetAllStudentRequestBody();
            inValue.Body.idClass = idClass;
            return ((Website.AdminService.Admin_ServiceSoap)(this)).GetAllStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.GetAllTeacherResponse Website.AdminService.Admin_ServiceSoap.GetAllTeacher(Website.AdminService.GetAllTeacherRequest request) {
            return base.Channel.GetAllTeacher(request);
        }
        
        public string GetAllTeacher(int idClass) {
            Website.AdminService.GetAllTeacherRequest inValue = new Website.AdminService.GetAllTeacherRequest();
            inValue.Body = new Website.AdminService.GetAllTeacherRequestBody();
            inValue.Body.idClass = idClass;
            Website.AdminService.GetAllTeacherResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).GetAllTeacher(inValue);
            return retVal.Body.GetAllTeacherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.GetAllTeacherResponse> Website.AdminService.Admin_ServiceSoap.GetAllTeacherAsync(Website.AdminService.GetAllTeacherRequest request) {
            return base.Channel.GetAllTeacherAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.GetAllTeacherResponse> GetAllTeacherAsync(int idClass) {
            Website.AdminService.GetAllTeacherRequest inValue = new Website.AdminService.GetAllTeacherRequest();
            inValue.Body = new Website.AdminService.GetAllTeacherRequestBody();
            inValue.Body.idClass = idClass;
            return ((Website.AdminService.Admin_ServiceSoap)(this)).GetAllTeacherAsync(inValue);
        }
        
        public bool AddStudentToClassCourse(int idClass, int idAccount) {
            return base.Channel.AddStudentToClassCourse(idClass, idAccount);
        }
        
        public System.Threading.Tasks.Task<bool> AddStudentToClassCourseAsync(int idClass, int idAccount) {
            return base.Channel.AddStudentToClassCourseAsync(idClass, idAccount);
        }
        
        public bool AddTeacherToClassCourse(int idClass, int idAccount) {
            return base.Channel.AddTeacherToClassCourse(idClass, idAccount);
        }
        
        public System.Threading.Tasks.Task<bool> AddTeacherToClassCourseAsync(int idClass, int idAccount) {
            return base.Channel.AddTeacherToClassCourseAsync(idClass, idAccount);
        }
        
        public bool RemoveStudentToClassCourse(int idClass, int idAccount) {
            return base.Channel.RemoveStudentToClassCourse(idClass, idAccount);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveStudentToClassCourseAsync(int idClass, int idAccount) {
            return base.Channel.RemoveStudentToClassCourseAsync(idClass, idAccount);
        }
        
        public bool RemoveAllStudentToClassCourse(int idClass) {
            return base.Channel.RemoveAllStudentToClassCourse(idClass);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveAllStudentToClassCourseAsync(int idClass) {
            return base.Channel.RemoveAllStudentToClassCourseAsync(idClass);
        }
        
        public bool RemoveTeacherToClassCourse(int idClass, int idAccount) {
            return base.Channel.RemoveTeacherToClassCourse(idClass, idAccount);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveTeacherToClassCourseAsync(int idClass, int idAccount) {
            return base.Channel.RemoveTeacherToClassCourseAsync(idClass, idAccount);
        }
        
        public bool RemoveAllTeacherToClassCourse(int idClass) {
            return base.Channel.RemoveAllTeacherToClassCourse(idClass);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveAllTeacherToClassCourseAsync(int idClass) {
            return base.Channel.RemoveAllTeacherToClassCourseAsync(idClass);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.FindStudentInSystemResponse Website.AdminService.Admin_ServiceSoap.FindStudentInSystem(Website.AdminService.FindStudentInSystemRequest request) {
            return base.Channel.FindStudentInSystem(request);
        }
        
        public string FindStudentInSystem(string key) {
            Website.AdminService.FindStudentInSystemRequest inValue = new Website.AdminService.FindStudentInSystemRequest();
            inValue.Body = new Website.AdminService.FindStudentInSystemRequestBody();
            inValue.Body.key = key;
            Website.AdminService.FindStudentInSystemResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).FindStudentInSystem(inValue);
            return retVal.Body.FindStudentInSystemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.FindStudentInSystemResponse> Website.AdminService.Admin_ServiceSoap.FindStudentInSystemAsync(Website.AdminService.FindStudentInSystemRequest request) {
            return base.Channel.FindStudentInSystemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.FindStudentInSystemResponse> FindStudentInSystemAsync(string key) {
            Website.AdminService.FindStudentInSystemRequest inValue = new Website.AdminService.FindStudentInSystemRequest();
            inValue.Body = new Website.AdminService.FindStudentInSystemRequestBody();
            inValue.Body.key = key;
            return ((Website.AdminService.Admin_ServiceSoap)(this)).FindStudentInSystemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.FindTeacherInSystemResponse Website.AdminService.Admin_ServiceSoap.FindTeacherInSystem(Website.AdminService.FindTeacherInSystemRequest request) {
            return base.Channel.FindTeacherInSystem(request);
        }
        
        public string FindTeacherInSystem(string key) {
            Website.AdminService.FindTeacherInSystemRequest inValue = new Website.AdminService.FindTeacherInSystemRequest();
            inValue.Body = new Website.AdminService.FindTeacherInSystemRequestBody();
            inValue.Body.key = key;
            Website.AdminService.FindTeacherInSystemResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).FindTeacherInSystem(inValue);
            return retVal.Body.FindTeacherInSystemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.FindTeacherInSystemResponse> Website.AdminService.Admin_ServiceSoap.FindTeacherInSystemAsync(Website.AdminService.FindTeacherInSystemRequest request) {
            return base.Channel.FindTeacherInSystemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.FindTeacherInSystemResponse> FindTeacherInSystemAsync(string key) {
            Website.AdminService.FindTeacherInSystemRequest inValue = new Website.AdminService.FindTeacherInSystemRequest();
            inValue.Body = new Website.AdminService.FindTeacherInSystemRequestBody();
            inValue.Body.key = key;
            return ((Website.AdminService.Admin_ServiceSoap)(this)).FindTeacherInSystemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.FindStudentInClassResponse Website.AdminService.Admin_ServiceSoap.FindStudentInClass(Website.AdminService.FindStudentInClassRequest request) {
            return base.Channel.FindStudentInClass(request);
        }
        
        public string FindStudentInClass(int idClass, string key) {
            Website.AdminService.FindStudentInClassRequest inValue = new Website.AdminService.FindStudentInClassRequest();
            inValue.Body = new Website.AdminService.FindStudentInClassRequestBody();
            inValue.Body.idClass = idClass;
            inValue.Body.key = key;
            Website.AdminService.FindStudentInClassResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).FindStudentInClass(inValue);
            return retVal.Body.FindStudentInClassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.FindStudentInClassResponse> Website.AdminService.Admin_ServiceSoap.FindStudentInClassAsync(Website.AdminService.FindStudentInClassRequest request) {
            return base.Channel.FindStudentInClassAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.FindStudentInClassResponse> FindStudentInClassAsync(int idClass, string key) {
            Website.AdminService.FindStudentInClassRequest inValue = new Website.AdminService.FindStudentInClassRequest();
            inValue.Body = new Website.AdminService.FindStudentInClassRequestBody();
            inValue.Body.idClass = idClass;
            inValue.Body.key = key;
            return ((Website.AdminService.Admin_ServiceSoap)(this)).FindStudentInClassAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Website.AdminService.FindTeacherInClassResponse Website.AdminService.Admin_ServiceSoap.FindTeacherInClass(Website.AdminService.FindTeacherInClassRequest request) {
            return base.Channel.FindTeacherInClass(request);
        }
        
        public string FindTeacherInClass(int idClass, string key) {
            Website.AdminService.FindTeacherInClassRequest inValue = new Website.AdminService.FindTeacherInClassRequest();
            inValue.Body = new Website.AdminService.FindTeacherInClassRequestBody();
            inValue.Body.idClass = idClass;
            inValue.Body.key = key;
            Website.AdminService.FindTeacherInClassResponse retVal = ((Website.AdminService.Admin_ServiceSoap)(this)).FindTeacherInClass(inValue);
            return retVal.Body.FindTeacherInClassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Website.AdminService.FindTeacherInClassResponse> Website.AdminService.Admin_ServiceSoap.FindTeacherInClassAsync(Website.AdminService.FindTeacherInClassRequest request) {
            return base.Channel.FindTeacherInClassAsync(request);
        }
        
        public System.Threading.Tasks.Task<Website.AdminService.FindTeacherInClassResponse> FindTeacherInClassAsync(int idClass, string key) {
            Website.AdminService.FindTeacherInClassRequest inValue = new Website.AdminService.FindTeacherInClassRequest();
            inValue.Body = new Website.AdminService.FindTeacherInClassRequestBody();
            inValue.Body.idClass = idClass;
            inValue.Body.key = key;
            return ((Website.AdminService.Admin_ServiceSoap)(this)).FindTeacherInClassAsync(inValue);
        }
    }
}
