//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.AdminServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminServiceReference.Admin_ServiceSoap")]
    public interface Admin_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Winform.AdminServiceReference.HelloWorldResponse HelloWorld(Winform.AdminServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.HelloWorldResponse> HelloWorldAsync(Winform.AdminServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCourseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCourse", ReplyAction="*")]
        Winform.AdminServiceReference.GetAllCourseResponse GetAllCourse(Winform.AdminServiceReference.GetAllCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.GetAllCourseResponse> GetAllCourseAsync(Winform.AdminServiceReference.GetAllCourseRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllClassCourseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllClassCourse", ReplyAction="*")]
        Winform.AdminServiceReference.GetAllClassCourseResponse GetAllClassCourse(Winform.AdminServiceReference.GetAllClassCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.GetAllClassCourseResponse> GetAllClassCourseAsync(Winform.AdminServiceReference.GetAllClassCourseRequest request);
        
        // CODEGEN: Generating message contract since element name GetClassCourseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClassCourse", ReplyAction="*")]
        Winform.AdminServiceReference.GetClassCourseResponse GetClassCourse(Winform.AdminServiceReference.GetClassCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.GetClassCourseResponse> GetClassCourseAsync(Winform.AdminServiceReference.GetClassCourseRequest request);
        
        // CODEGEN: Generating message contract since element name GetAcountInClassResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAcountInClass", ReplyAction="*")]
        Winform.AdminServiceReference.GetAcountInClassResponse GetAcountInClass(Winform.AdminServiceReference.GetAcountInClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAcountInClass", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.GetAcountInClassResponse> GetAcountInClassAsync(Winform.AdminServiceReference.GetAcountInClassRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllStudentResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStudent", ReplyAction="*")]
        Winform.AdminServiceReference.GetAllStudentResponse GetAllStudent(Winform.AdminServiceReference.GetAllStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.GetAllStudentResponse> GetAllStudentAsync(Winform.AdminServiceReference.GetAllStudentRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllTeacherResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTeacher", ReplyAction="*")]
        Winform.AdminServiceReference.GetAllTeacherResponse GetAllTeacher(Winform.AdminServiceReference.GetAllTeacherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTeacher", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.GetAllTeacherResponse> GetAllTeacherAsync(Winform.AdminServiceReference.GetAllTeacherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStudentToClassCourse", ReplyAction="*")]
        bool AddStudentToClassCourse(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStudentToClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddStudentToClassCourseAsync(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTeacherToClassCourse", ReplyAction="*")]
        bool AddTeacherToClassCourse(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTeacherToClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddTeacherToClassCourseAsync(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveStudentToClassCourse", ReplyAction="*")]
        bool RemoveStudentToClassCourse(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveStudentToClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RemoveStudentToClassCourseAsync(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveAllStudentToClassCourse", ReplyAction="*")]
        bool RemoveAllStudentToClassCourse(int idClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveAllStudentToClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RemoveAllStudentToClassCourseAsync(int idClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveTeacherToClassCourse", ReplyAction="*")]
        bool RemoveTeacherToClassCourse(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveTeacherToClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RemoveTeacherToClassCourseAsync(int idClass, int idAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveAllTeacherToClassCourse", ReplyAction="*")]
        bool RemoveAllTeacherToClassCourse(int idClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveAllTeacherToClassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RemoveAllTeacherToClassCourseAsync(int idClass);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindStudentInSystem", ReplyAction="*")]
        Winform.AdminServiceReference.FindStudentInSystemResponse FindStudentInSystem(Winform.AdminServiceReference.FindStudentInSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindStudentInSystem", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.FindStudentInSystemResponse> FindStudentInSystemAsync(Winform.AdminServiceReference.FindStudentInSystemRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindTeacherInSystem", ReplyAction="*")]
        Winform.AdminServiceReference.FindTeacherInSystemResponse FindTeacherInSystem(Winform.AdminServiceReference.FindTeacherInSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindTeacherInSystem", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.FindTeacherInSystemResponse> FindTeacherInSystemAsync(Winform.AdminServiceReference.FindTeacherInSystemRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindStudentInClass", ReplyAction="*")]
        Winform.AdminServiceReference.FindStudentInClassResponse FindStudentInClass(Winform.AdminServiceReference.FindStudentInClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindStudentInClass", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.FindStudentInClassResponse> FindStudentInClassAsync(Winform.AdminServiceReference.FindStudentInClassRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindTeacherInClass", ReplyAction="*")]
        Winform.AdminServiceReference.FindTeacherInClassResponse FindTeacherInClass(Winform.AdminServiceReference.FindTeacherInClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindTeacherInClass", ReplyAction="*")]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.FindTeacherInClassResponse> FindTeacherInClassAsync(Winform.AdminServiceReference.FindTeacherInClassRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Winform.AdminServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Winform.AdminServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCourse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.GetAllCourseRequestBody Body;
        
        public GetAllCourseRequest() {
        }
        
        public GetAllCourseRequest(Winform.AdminServiceReference.GetAllCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCourseRequestBody {
        
        public GetAllCourseRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.GetAllCourseResponseBody Body;
        
        public GetAllCourseResponse() {
        }
        
        public GetAllCourseResponse(Winform.AdminServiceReference.GetAllCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllCourseResult;
        
        public GetAllCourseResponseBody() {
        }
        
        public GetAllCourseResponseBody(string GetAllCourseResult) {
            this.GetAllCourseResult = GetAllCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllClassCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllClassCourse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.GetAllClassCourseRequestBody Body;
        
        public GetAllClassCourseRequest() {
        }
        
        public GetAllClassCourseRequest(Winform.AdminServiceReference.GetAllClassCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllClassCourseRequestBody {
        
        public GetAllClassCourseRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllClassCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllClassCourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.GetAllClassCourseResponseBody Body;
        
        public GetAllClassCourseResponse() {
        }
        
        public GetAllClassCourseResponse(Winform.AdminServiceReference.GetAllClassCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllClassCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllClassCourseResult;
        
        public GetAllClassCourseResponseBody() {
        }
        
        public GetAllClassCourseResponseBody(string GetAllClassCourseResult) {
            this.GetAllClassCourseResult = GetAllClassCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClassCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClassCourse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.GetClassCourseRequestBody Body;
        
        public GetClassCourseRequest() {
        }
        
        public GetClassCourseRequest(Winform.AdminServiceReference.GetClassCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetClassCourseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetClassCourseRequestBody() {
        }
        
        public GetClassCourseRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClassCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClassCourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.GetClassCourseResponseBody Body;
        
        public GetClassCourseResponse() {
        }
        
        public GetClassCourseResponse(Winform.AdminServiceReference.GetClassCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetClassCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetClassCourseResult;
        
        public GetClassCourseResponseBody() {
        }
        
        public GetClassCourseResponseBody(string GetClassCourseResult) {
            this.GetClassCourseResult = GetClassCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAcountInClassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAcountInClass", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.GetAcountInClassRequestBody Body;
        
        public GetAcountInClassRequest() {
        }
        
        public GetAcountInClassRequest(Winform.AdminServiceReference.GetAcountInClassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAcountInClassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idClass;
        
        public GetAcountInClassRequestBody() {
        }
        
        public GetAcountInClassRequestBody(int idClass) {
            this.idClass = idClass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAcountInClassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAcountInClassResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.GetAcountInClassResponseBody Body;
        
        public GetAcountInClassResponse() {
        }
        
        public GetAcountInClassResponse(Winform.AdminServiceReference.GetAcountInClassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAcountInClassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAcountInClassResult;
        
        public GetAcountInClassResponseBody() {
        }
        
        public GetAcountInClassResponseBody(string GetAcountInClassResult) {
            this.GetAcountInClassResult = GetAcountInClassResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStudent", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.GetAllStudentRequestBody Body;
        
        public GetAllStudentRequest() {
        }
        
        public GetAllStudentRequest(Winform.AdminServiceReference.GetAllStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idClass;
        
        public GetAllStudentRequestBody() {
        }
        
        public GetAllStudentRequestBody(int idClass) {
            this.idClass = idClass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.GetAllStudentResponseBody Body;
        
        public GetAllStudentResponse() {
        }
        
        public GetAllStudentResponse(Winform.AdminServiceReference.GetAllStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllStudentResult;
        
        public GetAllStudentResponseBody() {
        }
        
        public GetAllStudentResponseBody(string GetAllStudentResult) {
            this.GetAllStudentResult = GetAllStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTeacherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTeacher", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.GetAllTeacherRequestBody Body;
        
        public GetAllTeacherRequest() {
        }
        
        public GetAllTeacherRequest(Winform.AdminServiceReference.GetAllTeacherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTeacherRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idClass;
        
        public GetAllTeacherRequestBody() {
        }
        
        public GetAllTeacherRequestBody(int idClass) {
            this.idClass = idClass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTeacherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTeacherResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.GetAllTeacherResponseBody Body;
        
        public GetAllTeacherResponse() {
        }
        
        public GetAllTeacherResponse(Winform.AdminServiceReference.GetAllTeacherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTeacherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllTeacherResult;
        
        public GetAllTeacherResponseBody() {
        }
        
        public GetAllTeacherResponseBody(string GetAllTeacherResult) {
            this.GetAllTeacherResult = GetAllTeacherResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindStudentInSystemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindStudentInSystem", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.FindStudentInSystemRequestBody Body;
        
        public FindStudentInSystemRequest() {
        }
        
        public FindStudentInSystemRequest(Winform.AdminServiceReference.FindStudentInSystemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindStudentInSystemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public FindStudentInSystemRequestBody() {
        }
        
        public FindStudentInSystemRequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindStudentInSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindStudentInSystemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.FindStudentInSystemResponseBody Body;
        
        public FindStudentInSystemResponse() {
        }
        
        public FindStudentInSystemResponse(Winform.AdminServiceReference.FindStudentInSystemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindStudentInSystemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindStudentInSystemResult;
        
        public FindStudentInSystemResponseBody() {
        }
        
        public FindStudentInSystemResponseBody(string FindStudentInSystemResult) {
            this.FindStudentInSystemResult = FindStudentInSystemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindTeacherInSystemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindTeacherInSystem", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.FindTeacherInSystemRequestBody Body;
        
        public FindTeacherInSystemRequest() {
        }
        
        public FindTeacherInSystemRequest(Winform.AdminServiceReference.FindTeacherInSystemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindTeacherInSystemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public FindTeacherInSystemRequestBody() {
        }
        
        public FindTeacherInSystemRequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindTeacherInSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindTeacherInSystemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.FindTeacherInSystemResponseBody Body;
        
        public FindTeacherInSystemResponse() {
        }
        
        public FindTeacherInSystemResponse(Winform.AdminServiceReference.FindTeacherInSystemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindTeacherInSystemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindTeacherInSystemResult;
        
        public FindTeacherInSystemResponseBody() {
        }
        
        public FindTeacherInSystemResponseBody(string FindTeacherInSystemResult) {
            this.FindTeacherInSystemResult = FindTeacherInSystemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindStudentInClassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindStudentInClass", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.FindStudentInClassRequestBody Body;
        
        public FindStudentInClassRequest() {
        }
        
        public FindStudentInClassRequest(Winform.AdminServiceReference.FindStudentInClassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindStudentInClassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idClass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        public FindStudentInClassRequestBody() {
        }
        
        public FindStudentInClassRequestBody(int idClass, string key) {
            this.idClass = idClass;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindStudentInClassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindStudentInClassResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.FindStudentInClassResponseBody Body;
        
        public FindStudentInClassResponse() {
        }
        
        public FindStudentInClassResponse(Winform.AdminServiceReference.FindStudentInClassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindStudentInClassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindStudentInClassResult;
        
        public FindStudentInClassResponseBody() {
        }
        
        public FindStudentInClassResponseBody(string FindStudentInClassResult) {
            this.FindStudentInClassResult = FindStudentInClassResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindTeacherInClassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindTeacherInClass", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.FindTeacherInClassRequestBody Body;
        
        public FindTeacherInClassRequest() {
        }
        
        public FindTeacherInClassRequest(Winform.AdminServiceReference.FindTeacherInClassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindTeacherInClassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idClass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        public FindTeacherInClassRequestBody() {
        }
        
        public FindTeacherInClassRequestBody(int idClass, string key) {
            this.idClass = idClass;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindTeacherInClassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindTeacherInClassResponse", Namespace="http://tempuri.org/", Order=0)]
        public Winform.AdminServiceReference.FindTeacherInClassResponseBody Body;
        
        public FindTeacherInClassResponse() {
        }
        
        public FindTeacherInClassResponse(Winform.AdminServiceReference.FindTeacherInClassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindTeacherInClassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindTeacherInClassResult;
        
        public FindTeacherInClassResponseBody() {
        }
        
        public FindTeacherInClassResponseBody(string FindTeacherInClassResult) {
            this.FindTeacherInClassResult = FindTeacherInClassResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Admin_ServiceSoapChannel : Winform.AdminServiceReference.Admin_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Admin_ServiceSoapClient : System.ServiceModel.ClientBase<Winform.AdminServiceReference.Admin_ServiceSoap>, Winform.AdminServiceReference.Admin_ServiceSoap {
        
        public Admin_ServiceSoapClient() {
        }
        
        public Admin_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Admin_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Admin_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Admin_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AdminServiceReference.HelloWorldResponse Winform.AdminServiceReference.Admin_ServiceSoap.HelloWorld(Winform.AdminServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Winform.AdminServiceReference.HelloWorldRequest inValue = new Winform.AdminServiceReference.HelloWorldRequest();
            inValue.Body = new Winform.AdminServiceReference.HelloWorldRequestBody();
            Winform.AdminServiceReference.HelloWorldResponse retVal = ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.HelloWorldResponse> Winform.AdminServiceReference.Admin_ServiceSoap.HelloWorldAsync(Winform.AdminServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AdminServiceReference.HelloWorldResponse> HelloWorldAsync() {
            Winform.AdminServiceReference.HelloWorldRequest inValue = new Winform.AdminServiceReference.HelloWorldRequest();
            inValue.Body = new Winform.AdminServiceReference.HelloWorldRequestBody();
            return ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AdminServiceReference.GetAllCourseResponse Winform.AdminServiceReference.Admin_ServiceSoap.GetAllCourse(Winform.AdminServiceReference.GetAllCourseRequest request) {
            return base.Channel.GetAllCourse(request);
        }
        
        public string GetAllCourse() {
            Winform.AdminServiceReference.GetAllCourseRequest inValue = new Winform.AdminServiceReference.GetAllCourseRequest();
            inValue.Body = new Winform.AdminServiceReference.GetAllCourseRequestBody();
            Winform.AdminServiceReference.GetAllCourseResponse retVal = ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).GetAllCourse(inValue);
            return retVal.Body.GetAllCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.GetAllCourseResponse> Winform.AdminServiceReference.Admin_ServiceSoap.GetAllCourseAsync(Winform.AdminServiceReference.GetAllCourseRequest request) {
            return base.Channel.GetAllCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AdminServiceReference.GetAllCourseResponse> GetAllCourseAsync() {
            Winform.AdminServiceReference.GetAllCourseRequest inValue = new Winform.AdminServiceReference.GetAllCourseRequest();
            inValue.Body = new Winform.AdminServiceReference.GetAllCourseRequestBody();
            return ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).GetAllCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AdminServiceReference.GetAllClassCourseResponse Winform.AdminServiceReference.Admin_ServiceSoap.GetAllClassCourse(Winform.AdminServiceReference.GetAllClassCourseRequest request) {
            return base.Channel.GetAllClassCourse(request);
        }
        
        public string GetAllClassCourse() {
            Winform.AdminServiceReference.GetAllClassCourseRequest inValue = new Winform.AdminServiceReference.GetAllClassCourseRequest();
            inValue.Body = new Winform.AdminServiceReference.GetAllClassCourseRequestBody();
            Winform.AdminServiceReference.GetAllClassCourseResponse retVal = ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).GetAllClassCourse(inValue);
            return retVal.Body.GetAllClassCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.GetAllClassCourseResponse> Winform.AdminServiceReference.Admin_ServiceSoap.GetAllClassCourseAsync(Winform.AdminServiceReference.GetAllClassCourseRequest request) {
            return base.Channel.GetAllClassCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AdminServiceReference.GetAllClassCourseResponse> GetAllClassCourseAsync() {
            Winform.AdminServiceReference.GetAllClassCourseRequest inValue = new Winform.AdminServiceReference.GetAllClassCourseRequest();
            inValue.Body = new Winform.AdminServiceReference.GetAllClassCourseRequestBody();
            return ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).GetAllClassCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AdminServiceReference.GetClassCourseResponse Winform.AdminServiceReference.Admin_ServiceSoap.GetClassCourse(Winform.AdminServiceReference.GetClassCourseRequest request) {
            return base.Channel.GetClassCourse(request);
        }
        
        public string GetClassCourse(int id) {
            Winform.AdminServiceReference.GetClassCourseRequest inValue = new Winform.AdminServiceReference.GetClassCourseRequest();
            inValue.Body = new Winform.AdminServiceReference.GetClassCourseRequestBody();
            inValue.Body.id = id;
            Winform.AdminServiceReference.GetClassCourseResponse retVal = ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).GetClassCourse(inValue);
            return retVal.Body.GetClassCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.GetClassCourseResponse> Winform.AdminServiceReference.Admin_ServiceSoap.GetClassCourseAsync(Winform.AdminServiceReference.GetClassCourseRequest request) {
            return base.Channel.GetClassCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AdminServiceReference.GetClassCourseResponse> GetClassCourseAsync(int id) {
            Winform.AdminServiceReference.GetClassCourseRequest inValue = new Winform.AdminServiceReference.GetClassCourseRequest();
            inValue.Body = new Winform.AdminServiceReference.GetClassCourseRequestBody();
            inValue.Body.id = id;
            return ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).GetClassCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AdminServiceReference.GetAcountInClassResponse Winform.AdminServiceReference.Admin_ServiceSoap.GetAcountInClass(Winform.AdminServiceReference.GetAcountInClassRequest request) {
            return base.Channel.GetAcountInClass(request);
        }
        
        public string GetAcountInClass(int idClass) {
            Winform.AdminServiceReference.GetAcountInClassRequest inValue = new Winform.AdminServiceReference.GetAcountInClassRequest();
            inValue.Body = new Winform.AdminServiceReference.GetAcountInClassRequestBody();
            inValue.Body.idClass = idClass;
            Winform.AdminServiceReference.GetAcountInClassResponse retVal = ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).GetAcountInClass(inValue);
            return retVal.Body.GetAcountInClassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.GetAcountInClassResponse> Winform.AdminServiceReference.Admin_ServiceSoap.GetAcountInClassAsync(Winform.AdminServiceReference.GetAcountInClassRequest request) {
            return base.Channel.GetAcountInClassAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AdminServiceReference.GetAcountInClassResponse> GetAcountInClassAsync(int idClass) {
            Winform.AdminServiceReference.GetAcountInClassRequest inValue = new Winform.AdminServiceReference.GetAcountInClassRequest();
            inValue.Body = new Winform.AdminServiceReference.GetAcountInClassRequestBody();
            inValue.Body.idClass = idClass;
            return ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).GetAcountInClassAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AdminServiceReference.GetAllStudentResponse Winform.AdminServiceReference.Admin_ServiceSoap.GetAllStudent(Winform.AdminServiceReference.GetAllStudentRequest request) {
            return base.Channel.GetAllStudent(request);
        }
        
        public string GetAllStudent(int idClass) {
            Winform.AdminServiceReference.GetAllStudentRequest inValue = new Winform.AdminServiceReference.GetAllStudentRequest();
            inValue.Body = new Winform.AdminServiceReference.GetAllStudentRequestBody();
            inValue.Body.idClass = idClass;
            Winform.AdminServiceReference.GetAllStudentResponse retVal = ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).GetAllStudent(inValue);
            return retVal.Body.GetAllStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.GetAllStudentResponse> Winform.AdminServiceReference.Admin_ServiceSoap.GetAllStudentAsync(Winform.AdminServiceReference.GetAllStudentRequest request) {
            return base.Channel.GetAllStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AdminServiceReference.GetAllStudentResponse> GetAllStudentAsync(int idClass) {
            Winform.AdminServiceReference.GetAllStudentRequest inValue = new Winform.AdminServiceReference.GetAllStudentRequest();
            inValue.Body = new Winform.AdminServiceReference.GetAllStudentRequestBody();
            inValue.Body.idClass = idClass;
            return ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).GetAllStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AdminServiceReference.GetAllTeacherResponse Winform.AdminServiceReference.Admin_ServiceSoap.GetAllTeacher(Winform.AdminServiceReference.GetAllTeacherRequest request) {
            return base.Channel.GetAllTeacher(request);
        }
        
        public string GetAllTeacher(int idClass) {
            Winform.AdminServiceReference.GetAllTeacherRequest inValue = new Winform.AdminServiceReference.GetAllTeacherRequest();
            inValue.Body = new Winform.AdminServiceReference.GetAllTeacherRequestBody();
            inValue.Body.idClass = idClass;
            Winform.AdminServiceReference.GetAllTeacherResponse retVal = ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).GetAllTeacher(inValue);
            return retVal.Body.GetAllTeacherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.GetAllTeacherResponse> Winform.AdminServiceReference.Admin_ServiceSoap.GetAllTeacherAsync(Winform.AdminServiceReference.GetAllTeacherRequest request) {
            return base.Channel.GetAllTeacherAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AdminServiceReference.GetAllTeacherResponse> GetAllTeacherAsync(int idClass) {
            Winform.AdminServiceReference.GetAllTeacherRequest inValue = new Winform.AdminServiceReference.GetAllTeacherRequest();
            inValue.Body = new Winform.AdminServiceReference.GetAllTeacherRequestBody();
            inValue.Body.idClass = idClass;
            return ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).GetAllTeacherAsync(inValue);
        }
        
        public bool AddStudentToClassCourse(int idClass, int idAccount) {
            return base.Channel.AddStudentToClassCourse(idClass, idAccount);
        }
        
        public System.Threading.Tasks.Task<bool> AddStudentToClassCourseAsync(int idClass, int idAccount) {
            return base.Channel.AddStudentToClassCourseAsync(idClass, idAccount);
        }
        
        public bool AddTeacherToClassCourse(int idClass, int idAccount) {
            return base.Channel.AddTeacherToClassCourse(idClass, idAccount);
        }
        
        public System.Threading.Tasks.Task<bool> AddTeacherToClassCourseAsync(int idClass, int idAccount) {
            return base.Channel.AddTeacherToClassCourseAsync(idClass, idAccount);
        }
        
        public bool RemoveStudentToClassCourse(int idClass, int idAccount) {
            return base.Channel.RemoveStudentToClassCourse(idClass, idAccount);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveStudentToClassCourseAsync(int idClass, int idAccount) {
            return base.Channel.RemoveStudentToClassCourseAsync(idClass, idAccount);
        }
        
        public bool RemoveAllStudentToClassCourse(int idClass) {
            return base.Channel.RemoveAllStudentToClassCourse(idClass);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveAllStudentToClassCourseAsync(int idClass) {
            return base.Channel.RemoveAllStudentToClassCourseAsync(idClass);
        }
        
        public bool RemoveTeacherToClassCourse(int idClass, int idAccount) {
            return base.Channel.RemoveTeacherToClassCourse(idClass, idAccount);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveTeacherToClassCourseAsync(int idClass, int idAccount) {
            return base.Channel.RemoveTeacherToClassCourseAsync(idClass, idAccount);
        }
        
        public bool RemoveAllTeacherToClassCourse(int idClass) {
            return base.Channel.RemoveAllTeacherToClassCourse(idClass);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveAllTeacherToClassCourseAsync(int idClass) {
            return base.Channel.RemoveAllTeacherToClassCourseAsync(idClass);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AdminServiceReference.FindStudentInSystemResponse Winform.AdminServiceReference.Admin_ServiceSoap.FindStudentInSystem(Winform.AdminServiceReference.FindStudentInSystemRequest request) {
            return base.Channel.FindStudentInSystem(request);
        }
        
        public string FindStudentInSystem(string key) {
            Winform.AdminServiceReference.FindStudentInSystemRequest inValue = new Winform.AdminServiceReference.FindStudentInSystemRequest();
            inValue.Body = new Winform.AdminServiceReference.FindStudentInSystemRequestBody();
            inValue.Body.key = key;
            Winform.AdminServiceReference.FindStudentInSystemResponse retVal = ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).FindStudentInSystem(inValue);
            return retVal.Body.FindStudentInSystemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.FindStudentInSystemResponse> Winform.AdminServiceReference.Admin_ServiceSoap.FindStudentInSystemAsync(Winform.AdminServiceReference.FindStudentInSystemRequest request) {
            return base.Channel.FindStudentInSystemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AdminServiceReference.FindStudentInSystemResponse> FindStudentInSystemAsync(string key) {
            Winform.AdminServiceReference.FindStudentInSystemRequest inValue = new Winform.AdminServiceReference.FindStudentInSystemRequest();
            inValue.Body = new Winform.AdminServiceReference.FindStudentInSystemRequestBody();
            inValue.Body.key = key;
            return ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).FindStudentInSystemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AdminServiceReference.FindTeacherInSystemResponse Winform.AdminServiceReference.Admin_ServiceSoap.FindTeacherInSystem(Winform.AdminServiceReference.FindTeacherInSystemRequest request) {
            return base.Channel.FindTeacherInSystem(request);
        }
        
        public string FindTeacherInSystem(string key) {
            Winform.AdminServiceReference.FindTeacherInSystemRequest inValue = new Winform.AdminServiceReference.FindTeacherInSystemRequest();
            inValue.Body = new Winform.AdminServiceReference.FindTeacherInSystemRequestBody();
            inValue.Body.key = key;
            Winform.AdminServiceReference.FindTeacherInSystemResponse retVal = ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).FindTeacherInSystem(inValue);
            return retVal.Body.FindTeacherInSystemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.FindTeacherInSystemResponse> Winform.AdminServiceReference.Admin_ServiceSoap.FindTeacherInSystemAsync(Winform.AdminServiceReference.FindTeacherInSystemRequest request) {
            return base.Channel.FindTeacherInSystemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AdminServiceReference.FindTeacherInSystemResponse> FindTeacherInSystemAsync(string key) {
            Winform.AdminServiceReference.FindTeacherInSystemRequest inValue = new Winform.AdminServiceReference.FindTeacherInSystemRequest();
            inValue.Body = new Winform.AdminServiceReference.FindTeacherInSystemRequestBody();
            inValue.Body.key = key;
            return ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).FindTeacherInSystemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AdminServiceReference.FindStudentInClassResponse Winform.AdminServiceReference.Admin_ServiceSoap.FindStudentInClass(Winform.AdminServiceReference.FindStudentInClassRequest request) {
            return base.Channel.FindStudentInClass(request);
        }
        
        public string FindStudentInClass(int idClass, string key) {
            Winform.AdminServiceReference.FindStudentInClassRequest inValue = new Winform.AdminServiceReference.FindStudentInClassRequest();
            inValue.Body = new Winform.AdminServiceReference.FindStudentInClassRequestBody();
            inValue.Body.idClass = idClass;
            inValue.Body.key = key;
            Winform.AdminServiceReference.FindStudentInClassResponse retVal = ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).FindStudentInClass(inValue);
            return retVal.Body.FindStudentInClassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.FindStudentInClassResponse> Winform.AdminServiceReference.Admin_ServiceSoap.FindStudentInClassAsync(Winform.AdminServiceReference.FindStudentInClassRequest request) {
            return base.Channel.FindStudentInClassAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AdminServiceReference.FindStudentInClassResponse> FindStudentInClassAsync(int idClass, string key) {
            Winform.AdminServiceReference.FindStudentInClassRequest inValue = new Winform.AdminServiceReference.FindStudentInClassRequest();
            inValue.Body = new Winform.AdminServiceReference.FindStudentInClassRequestBody();
            inValue.Body.idClass = idClass;
            inValue.Body.key = key;
            return ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).FindStudentInClassAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Winform.AdminServiceReference.FindTeacherInClassResponse Winform.AdminServiceReference.Admin_ServiceSoap.FindTeacherInClass(Winform.AdminServiceReference.FindTeacherInClassRequest request) {
            return base.Channel.FindTeacherInClass(request);
        }
        
        public string FindTeacherInClass(int idClass, string key) {
            Winform.AdminServiceReference.FindTeacherInClassRequest inValue = new Winform.AdminServiceReference.FindTeacherInClassRequest();
            inValue.Body = new Winform.AdminServiceReference.FindTeacherInClassRequestBody();
            inValue.Body.idClass = idClass;
            inValue.Body.key = key;
            Winform.AdminServiceReference.FindTeacherInClassResponse retVal = ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).FindTeacherInClass(inValue);
            return retVal.Body.FindTeacherInClassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Winform.AdminServiceReference.FindTeacherInClassResponse> Winform.AdminServiceReference.Admin_ServiceSoap.FindTeacherInClassAsync(Winform.AdminServiceReference.FindTeacherInClassRequest request) {
            return base.Channel.FindTeacherInClassAsync(request);
        }
        
        public System.Threading.Tasks.Task<Winform.AdminServiceReference.FindTeacherInClassResponse> FindTeacherInClassAsync(int idClass, string key) {
            Winform.AdminServiceReference.FindTeacherInClassRequest inValue = new Winform.AdminServiceReference.FindTeacherInClassRequest();
            inValue.Body = new Winform.AdminServiceReference.FindTeacherInClassRequestBody();
            inValue.Body.idClass = idClass;
            inValue.Body.key = key;
            return ((Winform.AdminServiceReference.Admin_ServiceSoap)(this)).FindTeacherInClassAsync(inValue);
        }
    }
}
